### ISSUE TITLE
Fixing test_blob_trigger_with_large_content test in the CI end to end runs

### ISSUE THREAD

**Issue by vrdmr** [Azure/azure-functions-python-worker#1324]
We are seeing the following issue in the CI runs in the `test_blob_trigger_with_large_content` test. Investigate and fix this. Example run is [here](https://github.com/Azure/azure-functions-python-worker/actions/runs/6500784254/job/17662067189)

```python
[gw0] FAILED tests/endtoend/test_blob_functions.py::TestBlobFunctions::test_blob_trigger_with_large_content 
____________ TestBlobFunctions.test_blob_trigger_with_large_content ____________
[gw0] linux -- Python 3.9.18 /opt/hostedtoolcache/Python/3.9.18/x64/bin/python
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/runner/work/azure-functions-python-worker/azure-functions-python-worker/tests/utils/testutils.py", line 195, in wrapper
    return self._run_test(__meth__, *args, **kwargs)
  File "/home/runner/work/azure-functions-python-worker/azure-functions-python-worker/tests/utils/testutils.py", line 293, in _run_test
    raise test_exception
  File "/home/runner/work/azure-functions-python-worker/azure-functions-python-worker/tests/utils/testutils.py", line 281, in _run_test
    test(self, *args, **kwargs)
  File "/home/runner/work/azure-functions-python-worker/azure-functions-python-worker/tests/endtoend/test_blob_functions.py", line 145, in test_blob_trigger_with_large_content
    self.assertEqual(response['content'], data)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/unittest/case.py", line 837, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/unittest/case.py", line 1208, in assertMultiLineEqual
    self._baseAssertEqual(first, second, msg)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/unittest/case.py", line 830, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 'DummyData' != 'DummyDataDummyDataDummyDataDummyDataDummyDataDummy[[283](https://github.com/Azure/azure-functions-python-worker/actions/runs/6500784254/job/17656851030#step:10:284)11498 chars]Data'
------------------------------ Captured log call -------------------------------
```

**Comment by hallvictoria** [comment]
Issue is no longer happening, PR closed. We can reopen this if it starts happening again.
