### ISSUE TITLE
[BUG] Failure to debug Python Functions using VSCode + WSL2 + Ubuntu 22.04

### ISSUE THREAD

**Issue by qup9** [Azure/azure-functions-python-worker#1436]
Tools
- VSCode
- WSL2
- Ubuntu 22.04
- Python 3.10.12

I am using the Code created when using Workspace/New Project...
Project consistently fails with: **ConnectionRefusedError: [Errno 111]**

### Investigative information
I have tried everything I can find on the internet including #2808;
Python works on this VM;
I have deleted the project and started again and restarted WSl2

If I run:  _func host start / func start_ the function works with: p://localhost:7071/api/http_trigger1?name="test"

If I try to make a C# function works as expected.

I modified launch.json to include:       "command": "host start   --verbose",
Attached is the Output:

*  Executing task: .venv/bin/python -m pip install -r requirements.txt 

Requirement already satisfied: azure-functions in ./.venv/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (1.18.0)
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: . .venv/bin/activate && func host start   --verbose 

Found Python version 3.10.12 (python3).

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools
Core Tools Version:       4.0.5455 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.27.5.21554

[2024-02-23T18:20:57.501Z] Starting metrics publisher for container : wsl. Publishing endpoint is https://:31002/api/metrics
[2024-02-23T18:20:57.557Z] Initializing LinuxContainerActivityPublisher
[2024-02-23T18:20:57.557Z] Starting LinuxContainerActivityPublisher
MS_FUNCTION_LOGS 5,,,,,ScriptApplicationHostOptionsSetup,"","ScmRunFromPackage is empty.",4.27.5.21554,2024-02-23T18:20:57.5600849Z,,"",,,,WSL,,,,
[2024-02-23T18:20:57.607Z] Building host: version spec: , startup suppressed: 'False', configuration suppressed: 'False', startup operation id: '93a298d3-ebf7-4eac-aea6-e67cd4fb582f'
[2024-02-23T18:20:57.612Z] Reading host configuration file '/workspaces/functionApp/host.json'
[2024-02-23T18:20:57.613Z] Host configuration file read:
[2024-02-23T18:20:57.613Z] {
[2024-02-23T18:20:57.613Z]   "version": "2.0",
[2024-02-23T18:20:57.614Z]   "logging": {
[2024-02-23T18:20:57.614Z]     "applicationInsights": {
[2024-02-23T18:20:57.614Z]       "samplingSettings": {
[2024-02-23T18:20:57.614Z]         "isEnabled": true,
[2024-02-23T18:20:57.614Z]         "excludedTypes": "Request"
[2024-02-23T18:20:57.614Z]       }
[2024-02-23T18:20:57.614Z]     }
[2024-02-23T18:20:57.615Z]   },
[2024-02-23T18:20:57.615Z]   "extensionBundle": {
[2024-02-23T18:20:57.615Z]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2024-02-23T18:20:57.615Z]     "version": "[4.*, 5.0.0)"
[2024-02-23T18:20:57.615Z]   }
[2024-02-23T18:20:57.615Z] }
[2024-02-23T18:20:57.654Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language: powershell
[2024-02-23T18:20:57.665Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language: node
[2024-02-23T18:20:57.686Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language: java
[2024-02-23T18:20:57.687Z] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /FuncExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2024-02-23T18:20:57.687Z] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /root/site/wwwroot/.azurefunctions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2024-02-23T18:20:57.687Z] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /root/data/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2024-02-23T18:20:57.688Z] Found a matching extension bundle at /root/data/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.12.0
[2024-02-23T18:20:57.703Z] Loading functions metadata
[2024-02-23T18:20:57.705Z] Worker indexing is enabled
[2024-02-23T18:20:57.712Z] Fetching metadata for workerRuntime: python
[2024-02-23T18:20:57.712Z] Reading functions metadata (Worker)
[2024-02-23T18:20:58.383Z] Language Worker Process exited. Pid=2686.
[2024-02-23T18:20:58.383Z] python3 exited with code 1 (0x1). ConnectionRefusedError: [Errno 111] Connection refused,ConnectionRefusedError: [Errno 111] Connection refused.
[2024-02-23T18:21:02.566Z] Posting health event {"EventTime":"2024-02-23T18:21:02.5542407Z","EventType":0,"Source":"Microsoft.Azure.WebJobs.Script.WebHost.ContainerManagement.LinuxContainerActivityPublisher","Details":"SpecializationCompleted"}
[2024-02-23T18:21:02.578Z] PublishSpecializationCompleteEvent failed with System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
[2024-02-23T18:21:02.579Z]    at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
[2024-02-23T18:21:02.579Z]    at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
[2024-02-23T18:21:02.579Z]    at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
[2024-02-23T18:21:02.579Z]    at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request)
[2024-02-23T18:21:02.579Z]    at Microsoft.Azure.WebJobs.Script.WebHost.Management.MeshServiceClient.SendAsync(IEnumerable`1 formData) in /_/src/WebJobs.Script.WebHost/Management/MeshServiceClient.cs:line 154
[2024-02-23T18:21:02.579Z]    at Microsoft.Azure.WebJobs.Script.WebHost.Management.MeshServiceClient.NotifyHealthEvent(ContainerHealthEventType healthEventType, Type source, String details) in /_/src/WebJobs.Script.WebHost/Management/MeshServiceClient.cs:line 104
[2024-02-23T18:21:02.579Z]    at Microsoft.Azure.WebJobs.Script.WebHost.ContainerManagement.LinuxContainerActivityPublisher.PublishSpecializationCompleteEvent() in /_/src/WebJobs.Script.WebHost/ContainerManagement/LinuxContainerActivityPublisher.cs:line 122
MS_FUNCTION_METRICS ,,,hostjsonfileconfigurationsource.loadhostconfigurationsource.initializehostconfig,0,0,0,1,4.27.5.21554,2024-02-23T18:21:27.4964945Z,"{'IsStopwatchHighResolution': True}",WSL,,,,
MS_FUNCTION_METRICS ,,,hostjsonfileconfigurationsource.loadhostconfigurationsource.loadhostconfig,0,0,0,1,4.27.5.21554,2024-02-23T18:21:27.4964945Z,"{'IsStopwatchHighResolution': True}",WSL,,,,
MS_FUNCTION_METRICS ,,,workerconfigfactory.getconfigs.buildworkerproviderdictionary.addprovider./usr/lib/azure-functions-core-tools-4/workers/powershell,15,15,15,1,4.27.5.21554,2024-02-23T18:21:27.4964945Z,"{'IsStopwatchHighResolution': True}",WSL,,,,
MS_FUNCTION_METRICS ,,,workerconfigfactory.getconfigs.buildworkerproviderdictionary.addprovider./usr/lib/azure-functions-core-tools-4/workers/node,0,0,0,1,4.27.5.21554,2024-02-23T18:21:27.4964945Z,"{'IsStopwatchHighResolution': True}",WSL,,,,
MS_FUNCTION_METRICS ,,,workerconfigfactory.getconfigs.buildworkerproviderdictionary.addprovider./usr/lib/azure-functions-core-tools-4/workers/java,20,20,20,1,4.27.5.21554,2024-02-23T18:21:27.4964945Z,"{'IsStopwatchHighResolution': True}",WSL,,,,
MS_FUNCTION_METRICS ,,,workerconfigfactory.getconfigs.buildworkerproviderdictionary.addprovider./usr/lib/azure-functions-core-tools-4/workers/python,10,10,10,1,4.27.5.21554,2024-02-23T18:21:27.4964945Z,"{'IsStopwatchHighResolution': True}",WSL,,,,
MS_FUNCTION_METRICS ,,,hostjsonfileconfigurationsource.loadhostconfigurationsource,5,5,5,1,4.27.5.21554,2024-02-23T18:21:27.4964945Z,"{'IsStopwatchHighResolution': True}",WSL,,,,
MS_FUNCTION_METRICS ,,,workerprocess.start,5,5,5,1,4.27.5.21554,2024-02-23T18:21:27.4964945Z,"{'IsStopwatchHighResolution': True}",WSL,,,,
MS_FUNCTION_METRICS ,,,workerconfigfactory.getconfigs,49,49,49,1,4.27.5.21554,2024-02-23T18:21:27.4964945Z,"{'IsStopwatchHighResolution': True}",WSL,,,,
[2024-02-23T18:21:57.757Z] Starting worker process failed
[2024-02-23T18:21:57.757Z] Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.
[2024-02-23T18:21:57.759Z] Failed to start language worker process for runtime: (null). workerId:c8db8ef9-b555-4ed0-bf41-9ae967be7b64
[2024-02-23T18:21:57.761Z] Removing errored webhost language worker channel for runtime: python workerId:c8db8ef9-b555-4ed0-bf41-9ae967be7b64
[2024-02-23T18:21:57.761Z] Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.
[2024-02-23T18:21:57.786Z] 0 functions loaded
[2024-02-23T18:21:57.789Z] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /FuncExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2024-02-23T18:21:57.789Z] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /root/site/wwwroot/.azurefunctions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2024-02-23T18:21:57.789Z] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at /root/data/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle
[2024-02-23T18:21:57.789Z] Found a matching extension bundle at /root/data/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.12.0
[2024-02-23T18:21:57.790Z] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[2024-02-23T18:21:57.827Z] Skipping bundle download since it already exists at path /root/data/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.12.0
[2024-02-23T18:21:57.828Z] Loading extension bundle from /root/data/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.12.0/bin_v3/linux-x64
[2024-02-23T18:21:57.829Z] Script Startup resetting load context with base path: '/root/data/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/4.12.0/bin_v3/linux-x64'.
[2024-02-23T18:21:57.837Z] Reading host configuration file '/workspaces/functionApp/host.json'
[2024-02-23T18:21:57.837Z] Host configuration file read:
[2024-02-23T18:21:57.837Z] {
[2024-02-23T18:21:57.837Z]   "version": "2.0",
[2024-02-23T18:21:57.837Z]   "logging": {
[2024-02-23T18:21:57.837Z]     "applicationInsights": {
[2024-02-23T18:21:57.837Z]       "samplingSettings": {
[2024-02-23T18:21:57.837Z]         "isEnabled": true,
[2024-02-23T18:21:57.837Z]         "excludedTypes": "Request"
[2024-02-23T18:21:57.837Z]       }
[2024-02-23T18:21:57.837Z]     }
[2024-02-23T18:21:57.837Z]   },
[2024-02-23T18:21:57.837Z]   "extensionBundle": {
[2024-02-23T18:21:57.837Z]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[2024-02-23T18:21:57.837Z]     "version": "[4.*, 5.0.0)"
[2024-02-23T18:21:57.837Z]   }
[2024-02-23T18:21:57.837Z] }
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Workers Directory set to: /usr/lib/azure-functions-core-tools-4/workers",4.27.5.21554,2024-02-23T18:21:57.9843144Z,,"",,7719dbaf-0319-45f8-a0be-6dacebbe12c4,,WSL,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Found worker config: /usr/lib/azure-functions-core-tools-4/workers/powershell/worker.config.json",4.27.5.21554,2024-02-23T18:21:57.9845090Z,,"",,7719dbaf-0319-45f8-a0be-6dacebbe12c4,,WSL,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: python",4.27.5.21554,2024-02-23T18:21:57.9846553Z,,"",,7719dbaf-0319-45f8-a0be-6dacebbe12c4,,WSL,,,,
MS_FUNCTION_LOGS 4,,,,,Host.LanguageWorkerConfig,"","FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language: powershell",4.27.5.21554,2024-02-23T18:21:57.9855122Z,,"",,7719dbaf-0319-45f8-a0be-6dacebbe12c4,,WSL,,,,
[2024-02-23T18:21:57.992Z] MS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'wsl','message':'FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language: powershell','category':'Host.LanguageWorkerConfig','hostVersion':'4.27.5.21554','hostInstanceId':'7719dbaf-0319-45f8-a0be-6dacebbe12c4','level':'Information','levelId':2,'processId':2651}",WSL,,02/23/2024 18:21:57
FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language: powershell
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Found worker config: /usr/lib/azure-functions-core-tools-4/workers/python/worker.config.json",4.27.5.21554,2024-02-23T18:21:57.9927588Z,,"",,7719dbaf-0319-45f8-a0be-6dacebbe12c4,,WSL,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: python",4.27.5.21554,2024-02-23T18:21:57.9930990Z,,"",,7719dbaf-0319-45f8-a0be-6dacebbe12c4,,WSL,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME_VERSION: 3.10",4.27.5.21554,2024-02-23T18:21:57.9931523Z,,"",,7719dbaf-0319-45f8-a0be-6dacebbe12c4,,WSL,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Added WorkerConfig for language: python",4.27.5.21554,2024-02-23T18:21:57.9932030Z,,"",,7719dbaf-0319-45f8-a0be-6dacebbe12c4,,WSL,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","Found worker config: /usr/lib/azure-functions-core-tools-4/workers/node/worker.config.json",4.27.5.21554,2024-02-23T18:21:57.9932423Z,,"",,7719dbaf-0319-45f8-a0be-6dacebbe12c4,,WSL,,,,
MS_FUNCTION_LOGS 5,,,,,Host.LanguageWorkerConfig,"","EnvironmentVariable FUNCTIONS_WORKER_RUNTIME: python",4.27.5.21554,2024-02-23T18:21:57.9933990Z,,"",,7719dbaf-0319-45f8-a0be-6dacebbe12c4,,WSL,,,,
MS_FUNCTION_LOGS 4,,,,,Host.LanguageWorkerConfig,"","FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language: node",4.27.5.21554,2024-02-23T18:21:57.9934933Z,,"",,7719dbaf-0319-45f8-a0be-6dacebbe12c4,,WSL,,,,
[2024-02-23T18:21:57.993Z] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language: nodeMS_FUNCTION_AZURE_MONITOR_EVENT 4,localhost:7071,Microsoft.Web/sites/functions/log,FunctionAppLogs,,"{'appName':'','roleInstance':'wsl','message':'FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language: node','category':'Host.LanguageWorkerConfig','hostVersion':'4.27.5.21554','hostInstanceId':'7719dbaf-0319-45f8-a0be-6dacebbe12c4','level':'Information','levelId':2,'processId':2651}",WSL,,02/23/2024 18:21:57
...

**Comment by bhagyshricompany** [comment]
Hi @qup9  thanks for reporting please share the all steps  for repro which you tried.
Thanks

**Comment by hallvictoria** [comment]
Hi @qup9, is the issue only happening when trying to debug? Running the function with `func host start` works correctly?

Can you share all the steps for repro-ing? I'm able to debug and run using WSL without any errors. Here's the documentation references I used to set it up:
	- [Developing Azure Functions Locally](https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=linux%2Cisolated-process%2Cnode-v4%2Cpython-v2%2Chttp-trigger%2Ccontainer-apps&pivots=programming-language-python)
	- [Steps to install Azure Functions locally using WSL/Ubuntu](https://github.com/Azure/azure-functions-core-tools/issues/941)

**Comment by morphykuffour** [comment]
I am experiencing a similar issue when running normally on windows. I get following error:

Azure Functions Core Tools
Core Tools Version:       4.0.6610 Commit hash: N/A +0d55b5d7efe83d85d2b5c6e0b0a9c1b213e96256 (64-bit)
Function Runtime Version: 4.1036.1.23224
```
[2025-01-08T21:29:14.728Z] Requesting metadata from worker failed.
[2025-01-08T21:29:14.732Z] Microsoft.Azure.WebJobs.Script.Grpc: The operation has timed out.
```
 The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command .venv\Scripts\activate ; func host start" terminated with exit code: 1.

I can't seem to find any helpful resources online about this issue. Could this be a runtime version issue?
