### ISSUE TITLE
When I create the function app I get: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by ErlendFax** [Azure/azure-functions-python-worker#212]
I followed the instructions on how to make a HttpTrigger with python, however, when I run:
`az functionapp createpreviewapp -n myFunc -g myRg -l "westeurope" -s myStorageAcc79245 --runtime python --is-linux`
I get this in return:

> No module named '_cffi_backend'
> Traceback (most recent call last):
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/knack/cli.py", line 197, in invoke
>     cmd_result = self.invocation.execute(args)
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 262, in execute
>     self.commands_loader.load_arguments(command)
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 253, in load_arguments
>     self.command_table[command].load_arguments()  # this loads the arguments via reflection
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/commands/__init__.py", line 141, in load_arguments
>     super(AzCliCommand, self).load_arguments()
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/knack/commands.py", line 76, in load_arguments
>     cmd_args = self.arguments_loader()
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 440, in default_arguments_loader
>     op = handler or self.get_op_handler(operation)
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/core/__init__.py", line 485, in get_op_handler
>     op = import_module(mod_to_import)
>   File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/Users/erlendfaxvaag/.azure/cliextensions/functionapp/azext_functionapp/custom.py", line 23, in <module>
>     from azure.cli.command_modules.appservice.custom import (
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/azure/cli/command_modules/appservice/custom.py", line 19, in <module>
>     import OpenSSL.crypto
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import crypto, SSL
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/OpenSSL/crypto.py", line 12, in <module>
>     from cryptography import x509
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
>     from cryptography.x509.base import (
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/cryptography/x509/base.py", line 16, in <module>
>     from cryptography.x509.extensions import Extension, ExtensionType
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/cryptography/x509/extensions.py", line 18, in <module>
>     from cryptography.hazmat.primitives import constant_time, serialization
>   File "/usr/local/Cellar/azure-cli/2.0.44/libexec/lib/python3.7/site-packages/cryptography/hazmat/primitives/constant_time.py", line 11, in <module>
>     from cryptography.hazmat.bindings._constant_time import lib
> ModuleNotFoundError: No module named '_cffi_backend'

Looks like it uses my python 3.7 version? What causes this? Thank you!

**Comment by ErlendFax** [comment]
lol, solved by: pip install cffi on python 3.7
