### ISSUE TITLE
Event Grid Trigger not working

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-functions-python-worker#240]
Event Grid Trigger does not work, crashes when `func host start` command is issued:

Logs:

Azure Functions Core Tools (2.0.3)
Function Runtime Version: 2.0.12115.0
: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/Users/prananth/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
info: Host.General[0]
      Building host: startup suppressed:False, configuration suppressed: False
info: Host.Startup[0]
      Reading host configuration file '/Users/prananth/OneWeek-Table30/TestProj/host.json'
info: Host.Startup[0]
      Host configuration file read:
      {
        "version": "2.0"
      }
[11/25/18 7:44:04 AM] A host error has occurred
[11/25/18 7:44:04 AM] Microsoft.WindowsAzure.Storage: Settings must be of the form "name=value".
Listening on http://0.0.0.0:7071/
Hit CTRL-C to exit...
Settings must be of the form "name=value".
Application is shutting down...
info: Host.General[0]
      Initialization cancellation requested by runtime.
crit: Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor[9]
      An error occurred starting the application
System.AggregateException: One or more errors occurred. (The operation was canceled.) ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.<>c__DisplayClass29_0.<StartHostAsync>b__1(Task t) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 207
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.StartHostAsync(CancellationToken cancellationToken, Int32 attemptCount, JobHostStartupMode startupMode) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 204
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.StartAsync(CancellationToken cancellationToken) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 100
   at Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor.ExecuteAsync(Func`2 callback)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor.ExecuteAsync(Func`2 callback)
   at Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor.StartAsync(CancellationToken token)
---> (Inner Exception #0) System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.<>c__DisplayClass29_0.<StartHostAsync>b__1(Task t) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 207
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.StartHostAsync(CancellationToken cancellationToken, Int32 attemptCount, JobHostStartupMode startupMode) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 204
   at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.StartAsync(CancellationToken cancellationToken) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 100
   at Microsoft.AspNetCore.Hosting.Internal.HostedServiceExecutor.ExecuteAsync(Func`2 callback)<---

Hosting environment: Production
Content root path: /Users/prananth/OneWeek-Table30/TestProj
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
info: Host.General[0]
      Stopping host...
info: Host.General[0]

**Comment by elprans** [comment]
This doesn't look like a worker issue:

```
[11/25/18 7:44:04 AM] A host error has occurred
[11/25/18 7:44:04 AM] Microsoft.WindowsAzure.Storage: Settings must be of the form "name=value".
```

**Comment by maiqbal11** [comment]
Hi Priya, Are you specifying a valid storage account for your app? This is needed for all triggers except for HTTP. Someone had a similar issue as this, but with a timer trigger: #224.

**Comment by priyaananthasankar** [comment]
No I haven't specified a valid connection string. However this has to be mentioned in documentation or such if Webjobs SDK cannot be fixed, because it looks like a bug and the message is not intuitive either.

**Comment by asavaritayal** [comment]
/cc @ggailey777 for docs feedback

@priyaananthasankar can you please confirm if your app works with the storage setting?
