### ISSUE TITLE
Guys!!! I have filed three issues and no resolution so far!!!

### ISSUE THREAD

**Issue by fernandrez** [Azure/azure-functions-python-worker#263]
Guys!!! I have filed three issues and no resolution so far!!!
Please heeeeelp!!!! I need to get a python function working asap! please please help help!
#229 and #234 !!!

**Comment by fernandrez** [comment]
I can pay if necessary!

**Comment by fernandrez** [comment]
%%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.3.148 Commit hash: f9b3db04f9833b431f1b001efb3e5783a169ebfc)
Function Runtime Version: 2.0.12210.0
[11/12/2018 21:51:22] Building host: startup suppressed:False, configuration suppressed: False
[11/12/2018 21:51:22] Reading host configuration file 'C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\TimeToCritical\host.json'
[11/12/2018 21:51:22] Host configuration file read:
[11/12/2018 21:51:22] {
[11/12/2018 21:51:22]   "version": "2.0"
[11/12/2018 21:51:22] }
[11/12/2018 21:51:22] Initializing Host.
[11/12/2018 21:51:22] Host initialization: ConsecutiveErrors=0, StartupCount=1
[11/12/2018 21:51:22] Starting JobHost
[11/12/2018 21:51:22] Starting Host (HostId=ar2301649w1-717088189, InstanceId=fbfe86e2-388e-44cd-a221-4f4faaf7d942, Version=2.0.12210.0, ProcessId=27696, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=)
[11/12/2018 21:51:22] Loading functions metadata
[11/12/2018 21:51:22] 1 functions loaded
[11/12/2018 21:51:23] Starting language worker process:python  "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py" --host 127.0.0.1 --port 49388 --workerId 21719aba-bd90-43ad-82f8-e3669ee9b793 --requestId d5beb5bb-152e-4876-8cd7-66968ca0d326 --grpcMaxMessageLength 134217728
[11/12/2018 21:51:23] python process with Id=19520 started
[11/12/2018 21:51:23] Generating 1 job function(s)
[11/12/2018 21:51:23] Found the following functions:
[11/12/2018 21:51:23] Host.Functions.TTC_ARIMA
[11/12/2018 21:51:23]
[11/12/2018 21:51:23] Host initialized (384ms)
[11/12/2018 21:51:23] Host started (398ms)
[11/12/2018 21:51:23] Job host started
Hosting environment: Production
Content root path: C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\TimeToCritical
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.

Http Functions:

        TTC_ARIMA: [GET,POST] http://localhost:7071/api/TTC_ARIMA

[11/12/2018 21:51:28] Host lock lease acquired by instance ID '000000000000000000000000503DC8EE'.
[11/12/2018 21:51:29] Traceback (most recent call last):
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 29, in main
[11/12/2018 21:51:29] Traceback (most recent call last):
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 36, in <module>
[11/12/2018 21:51:29]     args.grpc_max_msg_len)
[11/12/2018 21:51:29]     main()[11/12/2018 21:51:29]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\__init__.py", line 16, in start

[11/12/2018 21:51:29]     host, port, worker_id, request_id, grpc_max_msg_len))
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 29, in main
[11/12/2018 21:51:29]     args.grpc_max_msg_len)
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\aio_compat.py", line 49, in run
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\__init__.py", line 16, in start
[11/12/2018 21:51:29]     return loop.run_until_complete(main)[11/12/2018 21:51:29]     host, port, worker_id, request_id, grpc_max_msg_len))

[11/12/2018 21:51:29]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\aio_compat.py", line 49, in run
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 468, in run_until_complete
[11/12/2018 21:51:29]     return loop.run_until_complete(main)
[11/12/2018 21:51:29]     return future.result()[11/12/2018 21:51:29]   File "C:\Users\ff824bv\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 468, in run_until_complete

[11/12/2018 21:51:29]     return future.result()
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\__init__.py", line 8, in start_async
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\__init__.py", line 8, in start_async
[11/12/2018 21:51:29]     connect_timeout=5.0, max_msg_len=grpc_max_msg_len)
[11/12/2018 21:51:29]     connect_timeout=5.0, max_msg_len=grpc_max_msg_len)
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\dispatcher.py", line 74, in connect
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\dispatcher.py", line 74, in connect
[11/12/2018 21:51:29]     await disp._grpc_connected_fut
[11/12/2018 21:51:29]     await disp._grpc_connected_fut
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\dispatcher.py", line 337, in __poll_grpc
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\dispatcher.py", line 337, in __poll_grpc
[11/12/2018 21:51:29]     timeout=self._grpc_connect_timeout)
[11/12/2018 21:51:29]     timeout=self._grpc_connect_timeout)
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\grpc\_utilities.py", line 134, in result[11/12/2018 21:51:29] Language Worker Process exited.

[11/12/2018 21:51:29]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\grpc\_utilities.py", line 134, in result
[11/12/2018 21:51:29]     self._block(timeout)[11/12/2018 21:51:29] python exited with code 1
 .

[11/12/2018 21:51:29]     self._block(timeout)
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\grpc\_utilities.py", line 84, in _block
[11/12/2018 21:51:29]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\grpc\_utilities.py", line 84, in _block
[11/12/2018 21:51:29]     raise grpc.FutureTimeoutError()
[11/12/2018 21:51:29]     raise grpc.FutureTimeoutError()
[11/12/2018 21:51:29] grpc.FutureTimeoutError
[11/12/2018 21:51:29] grpc.FutureTimeoutError
[11/12/2018 21:51:29] Starting language worker process:python  "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py" --host 127.0.0.1 --port 49388 --workerId ad0f051f-59bb-4441-b621-d68c98fa309c --requestId 97809fbd-e0a8-4ad0-87dc-a28e5ce8a22d --grpcMaxMessageLength 134217728
[11/12/2018 21:51:29] python process with Id=30764 started
[11/12/2018 21:51:35] Traceback (most recent call last):
[11/12/2018 21:51:35]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 29, in main
[11/12/2018 21:51:35]     args.grpc_max_msg_len)
[11/12/2018 21:51:35] Traceback (most recent call last):
[11/12/2018 21:51:35]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\__init__.py", line 16, in start
[11/12/2018 21:51:35]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 36, in <module>
[11/12/2018 21:51:35]     host, port, worker_id, request_id, grpc_max_msg_len))[11/12/2018 21:51:35]     main()

[11/12/2018 21:51:35]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\aio_compat.py", line 49, in run[11/12/2018 21:51:35]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 29, in main

[11/12/2018 21:51:35]     return loop.run_until_complete(main)
[11/12/2018 21:51:35]     args.grpc_max_msg_len)
[11/12/2018 21:51:35]   File "C:\Users\ff824bv\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 468, in run_until_complete
[11/12/2018 21:51:35] Language Worker Process exited.
[11/12/2018 21:51:35]     return future.result()
[11/12/2018 21:51:35] python exited with code 1
 .
[11/12/2018 21:51:35]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\__init__.py", line 8, in start_async
[11/12/2018 21:51:35] Starting language worker process:python  "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py" --host 127.0.0.1 --port 49388 --workerId dfff8a12-34c2-45bc-a1a6-dd46e3d543f3 --requestId e2a680b0-59b3-4aa8-835f-7068e226d362 --grpcMaxMessageLength 134217728
[11/12/2018 21:51:35]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\__init__.py", line 16, in start
[11/12/2018 21:51:35] python process with Id=35700 started
[11/12/2018 21:51:41] Traceback (most recent call last):
[11/12/2018 21:51:41]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 29, in main
[11/12/2018 21:51:41]     args.grpc_max_msg_len)
[11/12/2018 21:51:41] Traceback (most recent call last):
[11/12/2018 21:51:41]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 36, in <module>
[11/12/2018 21:51:41]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\__init__.py", line 16, in start[11/12/2018 21:51:41]     main()

[11/12/2018 21:51:41]     host, port, worker_id, request_id, grpc_max_msg_len))
[11/12/2018 21:51:41]   File "C:\Users\ff824bv\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\worker.py", line 29, in main
[11/12/2018 21:51:41]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\aio_compat.py", line 49, in run
[11/12/2018 21:51:41]     args.grpc_max_msg_len)
[11/12/2018 21:51:41]     return loop.run_until_complete(main)
[11/12/2018 21:51:41]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\__init__.py", line 16, in start
[11/12/2018 21:51:41]     host, port, worker_id, request_id, grpc_max_msg_len))
[11/12/2018 21:51:41]   File "C:\Users\ff824bv\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 468, in run_until_complete
[11/12/2018 21:51:41]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\aio_compat.py", line 49, in run[11/12/2018 21:51:41]     return future.result()

[11/12/2018 21:51:41]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\__init__.py", line 8, in start_async
[11/12/2018 21:51:41] Language Worker Process exited.
[11/12/2018 21:51:41]     connect_timeout=5.0, max_msg_len=grpc_max_msg_len)
[11/12/2018 21:51:41] python exited with code 1
 .
[11/12/2018 21:51:41]   File "C:\Users\ff824bv\Documents\Proyectos\Repos\CTP_Monitor\MMLEMT\Metrics\.env\lib\site-packages\azure\functions_worker\dispatcher.py", line 74, in connect
[11/12/2018 21:51:41]     return loop.run_until_complete(main)
[11/12/2018 21:52:07] Executing HTTP request: {
[11/12/2018 21:52:07]   "requestId": "f77565a7-ab84-41bc-b319-1a2885f40244",
[11/12/2018 21:52:07]   "method": "GET",
[11/12/2018 21:52:07]   "uri": "/api/TTC_ARIMA"
[11/12/2018 21:52:07] }
[11/12/2018 21:52:08] Executing 'Functions.TTC_ARIMA' (Reason='This function was programmatically called via the host APIs.', Id=92a430cd-d6e4-4620-a153-61bed43736e7)
[11/12/2018 21:52:08] Executed 'Functions.TTC_ARIMA' (Failed, Id=92a430cd-d6e4-4620-a153-61bed43736e7)
[11/12/2018 21:52:08] System.Private.CoreLib: Exception while executing function: Functions.TTC_ARIMA. System.Private.CoreLib: Failed to start language worker for: python. One or more errors occurred. (python exited with code 1
 ) (python exited with code 1
 ) (python exited with code 1
 ). python exited with code 1
 .
[11/12/2018 21:52:08] Executed HTTP request: {
[11/12/2018 21:52:08]   "requestId": "f77565a7-ab84-41bc-b319-1a2885f40244",
[11/12/2018 21:52:08]   "method": "GET",
[11/12/2018 21:52:08]   "uri": "/api/TTC_ARIMA",
[11/12/2018 21:52:08]   "identities": [
[11/12/2018 21:52:08]     {
[11/12/2018 21:52:08]       "type": "WebJobsAuthLevel",
[11/12/2018 21:52:08]       "level": "Admin"
[11/12/2018 21:52:08]     }
[11/12/2018 21:52:08]   ],
[11/12/2018 21:52:08]   "status": 500,
[11/12/2018 21:52:08]   "duration": 896
[11/12/2018 21:52:08] }

**Comment by elprans** [comment]
Judging from the traceback the worker seems to fail to open the gRPC channel to the functions host.  I would check that nothing is blocking network connections to high ports on the localhost (i.e. antivirus, firewall, etc).

**Comment by fernandrez** [comment]
I can say though that even if I start the azure function in a high port, the connection from the browser works and also fails at the worker

**Comment by fernandrez** [comment]
I am behind a proxy, but I did not mention this given the calls are going to be local anyways. Please help us out, the debugging cycle with us having to deploy to azure to test, is going to kill us.

**Comment by fernandrez** [comment]
I also see it's listening in both ports (host and worker):
TCP    127.0.0.1:59415        0.0.0.0:0              LISTENING
TCP    0.0.0.0:7071           0.0.0.0:0              LISTENING

**Comment by fernandrez** [comment]
Hi all, @elprans @maiqbal11, would you please redirect me somewhere?

**Comment by monteledwards** [comment]
This is not the way to ask for support. This is an in progress, highly beta service that the front page explicitly marks as to not use in production. This project, at the moment, is only for testing. I promise you the MSFT team is busy working to fix these issues... never spam a project like this.

**Comment by asavaritayal** [comment]
Closing issue in favor of the duplicate - https://github.com/Azure/azure-functions-python-worker/issues/229
