### ISSUE TITLE
Issue migrating existing V1 environment to V2

### ISSUE THREAD

**Issue by StefanVanDyck** [Azure/azure-functions-python-worker#266]
I am having issues deploying my code to the azure functions cloud environment.
I don't know if this is the right place to log this issue, let me know if I should use another channel.

I managed to migrate an existing V1 function runtime project to V2.
Everything is working perfectly fine locally, however when deploying on Azure I am running into issues.
I am trying to convert an existing environment to V2 (due to limited rights in creating new environments)

The python worker seems unable to start and the functions hosts error is unintelligible.
Seems there is some kind of Nullpointer error in the functions host when trying to determine the language.

#### Investigative information

- Function App name: BO-FUNC-WE-D-APPL-0001

- Potentially relevant application settings:
AzureWebJobsDashboard: Private
AzureWebJobsStorage: Private
fastCgi: D:\home\python364x64\python.exe
FUNCTION_APP_EDIT_MODE: readwrite
FUNCTIONS_EXTENSION_VERSION: ~2
FUNCTIONS_WORKER_RUNTIME: python
WEBSITE_HTTPLOGGING_RETENTION_DAYS 1
WEBSITE_USE_PLACEHOLDER 0

#### Repro steps

Provide the steps required to reproduce the problem:

Trying to run any python function, even threw away all functions and only kept:
```
def main():
    print('test')

print('ola')
```

#### Expected behavior

Simple print of _"ola"_ to and _"test"_ to the console.

#### Actual behavior

Function runtime is unable to start.

- Error log:
```
2018-12-13T13:35:29.100 [Information] Initializing Host.
2018-12-13T13:35:29.108 [Information] Host initialization: ConsecutiveErrors=0, StartupCount=1
2018-12-13T13:35:29.138 [Information] Starting JobHost
2018-12-13T13:35:29.146 [Information] Starting Host (HostId=bo-func-we-d-appl-0001, InstanceId=decfa6e7-c1fb-40d9-9cfd-b665b8ab9e2a, Version=2.0.12210.0, ProcessId=5476, AppDomainId=1, InDebugMode=True, InDiagnosticMode=False, FunctionsExtensionVersion=~2)
2018-12-13T13:35:29.174 [Information] Loading functions metadata
2018-12-13T13:35:29.541 [Information] 12 functions loaded
2018-12-13T13:35:29.753 [Error] A host error has occurred
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.Azure.WebJobs.Script.Utility.<>c__DisplayClass36_0.<ContainsFunctionWithCurrentLanguage>b__0(FunctionMetadata f) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 482
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source,Func`2 predicate)
   at Microsoft.Azure.WebJobs.Script.Utility.ContainsFunctionWithCurrentLanguage(IEnumerable`1 functions,String currentLanguage) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 482
   at Microsoft.Azure.WebJobs.Script.Utility.ShouldInitiliazeLanguageWorkers(IEnumerable`1 functions,String currentRuntimeLanguage) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 461
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.InitializeAsync() at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 270
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.StartAsyncCore(CancellationToken cancellationToken) at C:\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 250
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.StartHostAsync(CancellationToken cancellationToken,Int32 attemptCount,JobHostStartupMode startupMode) at C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs : 144
2018-12-13T13:35:29.835 [Information] Stopping JobHost
```

**Comment by StefanVanDyck** [comment]
I just realized the problem was my function app was using Windows instead of linux (Preview).
Pleas disregard, although the error might have been a bit more descriptive rather then a null-pointer
