### ISSUE TITLE
`func host start` does not properly load azure.functions

### ISSUE THREAD

**Issue by sptramer** [Azure/azure-functions-python-worker#270]
#### Investigative information

Env: Windows 10 CMD, Python 3.6 w/venv installed via installer, Azure Functions Core Tools installed via chocolatey package

Function created with:

`func init` (Python)
`func new` (HTTP Trigger)

Following instructions on: 

#### Repro steps

Provide the steps required to reproduce the problem:

1. `func host start`

#### Expected behavior

Application and python workers start as expected.

#### Actual behavior

Fails to start python worker:

```
(ENV) C:\Users\sttramer\src\azure-docs-cli-python\ci-merger>func host start

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.3.199 Commit hash: fdf734b09806be822e7d946fe17928b419d8a289)
Function Runtime Version: 2.0.12246.0
[12/28/2018 11:24:29 PM] Starting Rpc Initialization Service.
[12/28/2018 11:24:29 PM] Initializaing RpcServer
[12/28/2018 11:24:29 PM] Building host: startup suppressed:False, configuration suppressed: False
[12/28/2018 11:24:30 PM] Reading host configuration file 'C:\Users\sttramer\src\azure-docs-cli-python\ci-merger\host.json'
[12/28/2018 11:24:30 PM] Host configuration file read:
[12/28/2018 11:24:30 PM] {
[12/28/2018 11:24:30 PM]   "version": "2.0"
[12/28/2018 11:24:30 PM] }
[12/28/2018 11:24:30 PM] Initializing Host.
[12/28/2018 11:24:30 PM] Host initialization: ConsecutiveErrors=0, StartupCount=1
[12/28/2018 11:24:30 PM] Starting JobHost
[12/28/2018 11:24:30 PM] Starting Host (HostId=sttramerspro4-639159208, InstanceId=dc3e9338-9106-488e-b539-8c5077f10100, Version=2.0.12246.0, ProcessId=18980, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=)
[12/28/2018 11:24:30 PM] Loading functions metadata
[12/28/2018 11:24:30 PM] 1 functions loaded
[12/28/2018 11:24:30 PM] WorkerRuntime: python. Will shutdown other standby channels
[12/28/2018 11:24:30 PM] Starting language worker process:python  "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py" --host 127.0.0.1 --port 52822 --workerId d660bb33-ce01-4498-aede-e88eefe0d878 --requestId 19f23634-1710-43bb-9c26-d0b6468b802e --grpcMaxMessageLength 134217728
[12/28/2018 11:24:30 PM] python process with Id=19164 started
[12/28/2018 11:24:30 PM] Generating 1 job function(s)
[12/28/2018 11:24:30 PM] Found the following functions:
[12/28/2018 11:24:30 PM] Host.Functions.MergeExt
[12/28/2018 11:24:30 PM]
[12/28/2018 11:24:30 PM] Host initialized (209ms)
[12/28/2018 11:24:30 PM] Host started (222ms)
[12/28/2018 11:24:30 PM] Job host started
[12/28/2018 11:24:30 PM] Traceback (most recent call last):
[12/28/2018 11:24:30 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 36, in <module>
[12/28/2018 11:24:30 PM]     main()
[12/28/2018 11:24:30 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 23, in main
[12/28/2018 11:24:30 PM]     import azure.functions  # NoQA
[12/28/2018 11:24:30 PM] ModuleNotFoundError: No module named 'azure'
[12/28/2018 11:24:30 PM] Language Worker Process exited.
[12/28/2018 11:24:30 PM] python exited with code 1
 .
[12/28/2018 11:24:30 PM] Starting language worker process:python  "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py" --host 127.0.0.1 --port 52822 --workerId 9e890255-6327-42f3-abc1-d29a8733eb85 --requestId 590237f2-47d0-4336-8059-3159a465afca --grpcMaxMessageLength 134217728Hosting environment: Production
Content root path: C:\Users\sttramer\src\azure-docs-cli-python\ci-merger
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.

[12/28/2018 11:24:30 PM] python process with Id=11484 started

Http Functions:

        MergeExt: [GET,POST] http://localhost:7071/api/MergeExt

[12/28/2018 11:24:30 PM] Traceback (most recent call last):
[12/28/2018 11:24:30 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 36, in <module>
[12/28/2018 11:24:30 PM]     main()
[12/28/2018 11:24:30 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 23, in main
[12/28/2018 11:24:30 PM] Language Worker Process exited.
[12/28/2018 11:24:30 PM]     import azure.functions  # NoQA
[12/28/2018 11:24:30 PM] ModuleNotFoundError: No module named 'azure'
[12/28/2018 11:24:30 PM] python exited with code 1
 .
[12/28/2018 11:24:30 PM] Starting language worker process:python  "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py" --host 127.0.0.1 --port 52822 --workerId 82171357-eed5-4f7b-a9a1-79166d4783fb --requestId d71361db-dae7-4bc9-84d1-29fb0c4bb41f --grpcMaxMessageLength 134217728
[12/28/2018 11:24:30 PM] python process with Id=13564 started
[12/28/2018 11:24:31 PM] Traceback (most recent call last):
[12/28/2018 11:24:31 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 36, in <module>
[12/28/2018 11:24:31 PM]     main()
[12/28/2018 11:24:31 PM]   File "C:\ProgramData\chocolatey\lib\azure-functions-core-tools\tools\workers\python\worker.py", line 23, in main
[12/28/2018 11:24:31 PM] Language Worker Process exited.
[12/28/2018 11:24:31 PM]     import azure.functions  # NoQA
[12/28/2018 11:24:31 PM] python exited with code 1
 .
[12/28/2018 11:24:31 PM] ModuleNotFoundError: No module named 'azure'
[12/28/2018 11:24:35 PM] Host lock lease acquired by instance ID '000000000000000000000000792E1ADF'.
Application is shutting down...
```

#### Related information 

When starting python3 in the venv, `azure.functions` can be loaded as a module:

```
(ENV) C:\Users\sttramer\src\azure-docs-cli-python\ci-merger>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import azure.functions
>>> exit
```

**Comment by asavaritayal** [comment]
This issue was moved to Azure/azure-functions-core-tools#954
