### ISSUE TITLE
Latest versions of packages gives AttributeError for "start" when running locally

### ISSUE THREAD

**Issue by michhar** [Azure/azure-functions-python-worker#363]
Installed latest Azure Functions and Azure Functions Python Worker packages today and getting a `AttributeError: module 'azure.functions_worker' has no attribute 'start'.` when running `func host start` for local testing.  The previous version of the packages worked without errors.

Package versions used (latest as of today):
```
azure-functions==1.0.0b3
azure-functions-worker==1.0.0b4
```

Package versions that worked previously, with same code:
```
azure-functions==1.0.0a5
azure-functions-worker==1.0.0a6
```

#### Investigative information

Please provide the following:

- Timestamp:  3/16/19 6:24:49 AM
- Function App name:  Local
- Function name(s) (as appropriate):  NA
- Core Tools version: 2.3.199

#### Repro steps

Provide the steps required to reproduce the problem:

1.  Clone https://github.com/michhar/deeplearning-aml-and-azure-functions
2. Follow instructions for local testing

#### Expected behavior

No error messages when running `func host start` for this project locally.

#### Actual behavior

When running `func host start` this error trace appears:

```
(.env) <user name>$ func host start

                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Azure Functions Core Tools (2.3.199 Commit hash: fdf734b09806be822e7d946fe17928b419d8a289)
Function Runtime Version: 2.0.12246.0
[3/16/19 6:24:43 AM] Starting Rpc Initialization Service.
[3/16/19 6:24:43 AM] Initializaing RpcServer
[3/16/19 6:24:43 AM] Building host: startup suppressed:False, configuration suppressed: False
[3/16/19 6:24:43 AM] Reading host configuration file '/Users/micheleenharris/Documents/bin/github/train-dnn-aml-and-azure-function/dnn/host.json'
[3/16/19 6:24:43 AM] Host configuration file read:
[3/16/19 6:24:43 AM] {
[3/16/19 6:24:43 AM]   "version": "2.0"
[3/16/19 6:24:43 AM] }
[3/16/19 6:24:44 AM] Initializing Host.
[3/16/19 6:24:44 AM] Host initialization: ConsecutiveErrors=0, StartupCount=1
[3/16/19 6:24:44 AM] Starting JobHost
[3/16/19 6:24:44 AM] Starting Host (HostId=umwhat-1889644284, InstanceId=16368212-022a-4ac6-8ce8-5572f1f23ec4, Version=2.0.12246.0, ProcessId=79332, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=)
[3/16/19 6:24:44 AM] Loading functions metadata
[3/16/19 6:24:44 AM] 1 functions loaded
[3/16/19 6:24:44 AM] WorkerRuntime: python. Will shutdown other standby channels
[3/16/19 6:24:44 AM] Starting language worker process:python  "/usr/local/Cellar/azure-functions-core-tools/2.3.199/workers/python/worker.py" --host 127.0.0.1 --port 51660 --workerId b35b9981-54b1-415f-aded-66efbc05e798 --requestId b6a33d5f-59b3-4a2b-b2d5-83438db86071 --grpcMaxMessageLength 134217728
[3/16/19 6:24:44 AM] python process with Id=79337 started
[3/16/19 6:24:44 AM] Generating 1 job function(s)
[3/16/19 6:24:44 AM] Found the following functions:
[3/16/19 6:24:44 AM] Host.Functions.HttpTrigger
[3/16/19 6:24:44 AM] 
[3/16/19 6:24:44 AM] Host initialized (195ms)
[3/16/19 6:24:44 AM] Host started (204ms)
[3/16/19 6:24:44 AM] Job host started
[3/16/19 6:24:44 AM] Traceback (most recent call last):
[3/16/19 6:24:44 AM]   File "/usr/local/Cellar/azure-functions-core-tools/2.3.199/workers/python/worker.py", line 27, in main
[3/16/19 6:24:44 AM]     azure.functions_worker.start(
[3/16/19 6:24:44 AM] AttributeError: module 'azure.functions_worker' has no attribute 'start'
[3/16/19 6:24:44 AM] Traceback (most recent call last):
[3/16/19 6:24:44 AM]   File "/usr/local/Cellar/azure-functions-core-tools/2.3.199/workers/python/worker.py", line 36, in <module>
[3/16/19 6:24:44 AM]     main()
[3/16/19 6:24:44 AM]   File "/usr/local/Cellar/azure-functions-core-tools/2.3.199/workers/python/worker.py", line 27, in main
[3/16/19 6:24:44 AM]     azure.functions_worker.start(
[3/16/19 6:24:44 AM] AttributeError: module 'azure.functions_worker' has no attribute 'start'
[3/16/19 6:24:44 AM] Language Worker Process exited.
[3/16/19 6:24:44 AM] python exited with code 1
[3/16/19 6:24:44 AM]  AttributeError: module 'azure.functions_worker' has no attribute 'start'.
[3/16/19 6:24:44 AM] Starting language worker process:python  "/usr/local/Cellar/azure-functions-core-tools/2.3.199/workers/python/worker.py" --host 127.0.0.1 --port 51660 --workerId bf132308-e201-4c94-8f86-36dff2885d66 --requestId c5bce286-879e-4462-915f-c6af80e0e96c --grpcMaxMessageLength 134217728
[3/16/19 6:24:44 AM] python process with Id=79338 started
Hosting environment: Production
Content root path: /Users/micheleenharris/Documents/bin/github/train-dnn-aml-and-azure-function/dnn
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.

Http Functions:

        HttpTrigger: [GET,POST] http://localhost:7071/api/HttpTrigger

[3/16/19 6:24:44 AM] Traceback (most recent call last):
[3/16/19 6:24:44 AM]   File "/usr/local/Cellar/azure-functions-core-tools/2.3.199/workers/python/worker.py", line 27, in main
[3/16/19 6:24:44 AM]     azure.functions_worker.start(
[3/16/19 6:24:44 AM] AttributeError: module 'azure.functions_worker' has no attribute 'start'
[3/16/19 6:24:44 AM] Traceback (most recent call last):
[3/16/19 6:24:44 AM]   File "/usr/local/Cellar/azure-functions-core-tools/2.3.199/workers/python/worker.py", line 36, in <module>
[3/16/19 6:24:44 AM]     main()
[3/16/19 6:24:44 AM]   File "/usr/local/Cellar/azure-functions-core-tools/2.3.199/workers/python/worker.py", line 27, in main
[3/16/19 6:24:44 AM]     azure.functions_worker.start(
[3/16/19 6:24:44 AM] AttributeError: module 'azure.functions_worker' has no attribute 'start'
[3/16/19 6:24:44 AM] Language Worker Process exited.
[3/16/19 6:24:44 AM] python exited with code 1
[3/16/19 6:24:44 AM]  AttributeError: module 'azure.functions_worker' has no attribute 'start'.
[3/16/19 6:24:44 AM] Starting language worker process:python  "/usr/local/Cellar/azure-functions-core-tools/2.3.199/workers/python/worker.py" --host 127.0.0.1 --port 51660 --workerId 138aa15c-c8d8-4b9c-9947-c8ba3c9ba9c5 --requestId dd622262-d5e3-4e32-80d9-7a0704038d59 --grpcMaxMessageLength 134217728
[3/16/19 6:24:44 AM] python process with Id=79339 started
[3/16/19 6:24:44 AM] Traceback (most recent call last):
[3/16/19 6:24:44 AM]   File "/usr/local/Cellar/azure-functions-core-tools/2.3.199/workers/python/worker.py", line 27, in main
[3/16/19 6:24:44 AM]     azure.functions_worker.start(
[3/16/19 6:24:44 AM] AttributeError: module 'azure.functions_worker' has no attribute 'start'
[3/16/19 6:24:44 AM] Traceback (most recent call last):
[3/16/19 6:24:44 AM]   File "/usr/local/Cellar/azure-functions-core-tools/2.3.199/workers/python/worker.py", line 36, in <module>
[3/16/19 6:24:44 AM]     main()
[3/16/19 6:24:44 AM]   File "/usr/local/Cellar/azure-functions-core-tools/2.3.199/workers/python/worker.py", line 27, in main
[3/16/19 6:24:44 AM]     azure.functions_worker.start(
[3/16/19 6:24:44 AM] AttributeError: module 'azure.functions_worker' has no attribute 'start'
[3/16/19 6:24:44 AM] Language Worker Process exited.
[3/16/19 6:24:44 AM] python exited with code 1
[3/16/19 6:24:44 AM]  AttributeError: module 'azure.functions_worker' has no attribute 'start'.
[3/16/19 6:24:49 AM] Host lock lease acquired by instance ID '00000000000000000000000034C62831'.
```

Note:  a new virtual environment was also tried without success.

#### Known workarounds

Blocker with no known workarounds.

#### Related information 

Provide any related information 

* Links to source:  https://github.com/michhar/deeplearning-aml-and-azure-functions (function in `dnn` folder)

* Requirements file:
```
azure-functions==1.0.0b3
azure-functions-worker==1.0.0b4
grpcio==1.14.2
grpcio-tools==1.14.2
protobuf==3.6.1
six==1.12.0
azureml-sdk==1.0.18
requests==2.20.1
scikit-image==0.14.2
scikit-learn==0.20.2
```

* Bindings used

**Comment by michhar** [comment]
UPDATE:  I upgraded my `azure-functions-core-tools` to `2.4.419` and it fixed this problem.  Thanks.  Closing.
