### ISSUE TITLE
App crashed and not starting, Exceeded language worker restart retry count for runtime:python.

### ISSUE THREAD

**Issue by dmitrysmirnovfinnair** [Azure/azure-functions-python-worker#523]
I had an app which was running fine. Then after 11th July 2019 it stopped, and didn't start since then.
As I already got used to, the Azure portal UI is barely working, but once I managed to reach the part of UI where I could run the function manually, when I did so, logs had following errors:
```
2019-07-23T11:56:33.038361742Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Startup[413]
2019-07-23T11:56:33.038376242Z: [INFO]        Host started (2716ms)
2019-07-23T11:56:33.040931915Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Startup[0]
2019-07-23T11:56:33.040945015Z: [INFO]        Job host started
2019-07-23T11:56:33.057034147Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.057049447Z: [INFO]        python == /usr/local/bin/python
2019-07-23T11:56:33.058203535Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.058217035Z: [INFO]        PYTHONPATH == /home/site/wwwroot/.python_packages/lib/python3.6/site-packages:/home/site/wwwroot/worker_venv/lib/python3.6/site-packages:
2019-07-23T11:56:33.059383423Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.059396423Z: [INFO]        starting the python worker
2019-07-23T11:56:33.062643989Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.062658588Z: [INFO]        Traceback (most recent call last):
2019-07-23T11:56:33.072469286Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.072484186Z: [INFO]          File "/azure-functions-host/workers/python/worker.py", line 1, in <module>
2019-07-23T11:56:33.073664073Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.073677473Z: [INFO]            from azure.functions_worker import main
2019-07-23T11:56:33.074860461Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.074891261Z: [INFO]        ImportError: cannot import name 'main'
2019-07-23T11:56:33.076043149Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.076055749Z: [INFO]        python == /usr/local/bin/python
2019-07-23T11:56:33.077432934Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.077446134Z: [INFO]        PYTHONPATH == /home/site/wwwroot/.python_packages/lib/python3.6/site-packages:/home/site/wwwroot/worker_venv/lib/python3.6/site-packages:
2019-07-23T11:56:33.078619922Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:33.078632922Z: [INFO]        starting the python worker
2019-07-23T11:56:33.190065658Z: [INFO]  Hosting environment: Production
2019-07-23T11:56:33.190613252Z: [INFO]  Content root path: /
2019-07-23T11:56:33.191291045Z: [INFO]  Now listening on: http://[::]:80
2019-07-23T11:56:33.191828939Z: [INFO]  Application started. Press Ctrl+C to shut down.
2019-07-23T11:56:34.556553086Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:34.556575286Z: [INFO]        Traceback (most recent call last):
2019-07-23T11:56:34.557325078Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:34.557337178Z: [INFO]          File "/azure-functions-host/workers/python/worker.py", line 1, in <module>
2019-07-23T11:56:34.557350178Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:34.557354478Z: [INFO]            from azure.functions_worker import main
2019-07-23T11:56:34.558521065Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:34.558550265Z: [INFO]        ImportError: cannot import name 'main'
2019-07-23T11:56:34.632708391Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:34.632732990Z: [INFO]        python == /usr/local/bin/python
2019-07-23T11:56:34.633083087Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:34.633094387Z: [INFO]        PYTHONPATH == /home/site/wwwroot/.python_packages/lib/python3.6/site-packages:/home/site/wwwroot/worker_venv/lib/python3.6/site-packages:
2019-07-23T11:56:34.633099287Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:34.633103486Z: [INFO]        starting the python worker
2019-07-23T11:56:33.721066212Z: [INFO]  [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
2019-07-23T11:56:33.721103912Z: [INFO]        Request starting HTTP/1.1 GET http://127.0.0.1:55715/robots933456.txt  
2019-07-23T11:56:33.968921523Z: [INFO]  [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
2019-07-23T11:56:33.968971323Z: [INFO]        Request finished in 249.9744ms 404 
2019-07-23T11:56:33.995906941Z: [INFO]  [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
2019-07-23T11:56:33.995921641Z: [INFO]        Request starting HTTP/1.1 GET http://marimekkodataloaders.azurewebsites.net/admin/host/ping  
2019-07-23T11:56:34.342217025Z: [INFO]  [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
2019-07-23T11:56:34.342252224Z: [INFO]        Request finished in 346.2976ms 200 
2019-07-23T11:56:35.947894755Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:35.947932054Z: [INFO]        Traceback (most recent call last):
2019-07-23T11:56:35.952448807Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:35.952462607Z: [INFO]          File "/azure-functions-host/workers/python/worker.py", line 1, in <module>
2019-07-23T11:56:35.953008401Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:35.953020001Z: [INFO]            from azure.functions_worker import main
2019-07-23T11:56:35.954113790Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Function.Console[0]
2019-07-23T11:56:35.954126990Z: [INFO]        ImportError: cannot import name 'main'
2019-07-23T11:56:36.014461759Z: [INFO]  [41m[30mfail[39m[22m[49m: Microsoft.Azure.WebJobs.Script.Rpc.FunctionDispatcher[0]
2019-07-23T11:56:36.014484059Z: [INFO]        Exceeded language worker restart retry count for runtime:python. Shutting down Functions Host
2019-07-23T11:56:36.260561789Z: [INFO]  [40m[32minfo[39m[22m[49m: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]
2019-07-23T11:56:36.260616789Z: [INFO]        Stopping JobHost
2019-07-23T11:56:36.292887452Z: [INFO]  [40m[32minfo[39m[22m[49m: Host.Startup[0]
2019-07-23T11:56:36.292905051Z: [INFO]        Job host stopped
2019-07-23T11:56:36.326499100Z: [INFO]  Application is shutting down...
```

Now I decided to try to redeploy, so I did, and after a few building steps I get error, and the last thing in the log is:
```
Running 'docker exec -t 222984 /python_docker_build.sh'.> docker exec -t 222984c8a2fbf20bca21b3c97fd76055a7a6de77672185aac78a6f22d718828b /python_docker_build.sh
.....................done
Running 'docker kill 222984'.> docker kill 222984c8a2fbf20bca21b3c97fd76055a7a6de77672185aac78a6f22d718828b
.done
Output:

Error: Error response from daemon: Cannot kill container: 222984c8a2fbf20bca21b3c97fd76055a7a6de77672185aac78a6f22d718828b: Container 222984c8a2fbf20bca21b3c97fd76055a7a6de77672185aac78a6f22d718828b is not running
```
Any ideas for debugging or fixing it are welcome!

**Comment by kulkarnisonia16** [comment]
We made changes during preview, which might have caused this. This should be stable now. Let us know if this is still an issue. Thanks!

**Comment by leonidasnascimento** [comment]
Hi guys! 

I am facing the very same issue now. Can someone provide me a help? The log is bellow...

Azure Functions Core Tools (2.7.2254 Commit hash: ae06bd1a6012aa6a0859b5f30d3077947267d2b6)
Function Runtime Version: 2.0.13017.0
[05/03/2020 12:46:30] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:java
[05/03/2020 12:46:30] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:node
[05/03/2020 12:46:30] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:powershell
[05/03/2020 12:46:30] Building host: startup suppressed: 'False', configuration suppressed: 'False', startup operation id: '95bd42f4-1ad7-48b3-bc2f-320740d3ee3a'
[05/03/2020 12:46:30] Reading host configuration file 'c:\git\sosi_func0010_dividend_analysis\host.json'
[05/03/2020 12:46:30] Host configuration file read:
[05/03/2020 12:46:30] {
[05/03/2020 12:46:30]   "version": "2.0",
[05/03/2020 12:46:30]   "functionTimeout": "00:10:00",
[05/03/2020 12:46:30]   "extensionBundle": {
[05/03/2020 12:46:30]     "id": "Microsoft.Azure.Functions.ExtensionBundle",
[05/03/2020 12:46:30]     "version": "[1.*, 2.0.0)"
[05/03/2020 12:46:30]   }
[05/03/2020 12:46:30] }
[05/03/2020 12:46:31] Reading functions metadata
[05/03/2020 12:46:31] 1 functions found
[05/03/2020 12:46:31] Looking for extension bundle Microsoft.Azure.Functions.ExtensionBundle at C:\Users\leonidas.nascimento\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle
[05/03/2020 12:46:31] Found a matching extension bundle at C:\Users\leonidas.nascimento\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\1.1.1
[05/03/2020 12:46:31] Fetching information on versions of extension bundle Microsoft.Azure.Functions.ExtensionBundle available on https://functionscdn.azureedge.net/public/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/index.json
[05/03/2020 12:46:31] Skipping bundle download since it already exists at path C:\Users\leonidas.nascimento\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\1.1.1
[05/03/2020 12:46:31] Loading Extention bundle from C:\Users\leonidas.nascimento\AppData\Local\Temp\Functions\ExtensionBundles\Microsoft.Azure.Functions.ExtensionBundle\1.1.1
[05/03/2020 12:46:33] Initializing Warmup Extension.
[05/03/2020 12:46:33] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:java
[05/03/2020 12:46:33] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:node
[05/03/2020 12:46:34] FUNCTIONS_WORKER_RUNTIME set to python. Skipping WorkerConfig for language:powershell
[05/03/2020 12:46:34] Initializing Host. OperationId: '95bd42f4-1ad7-48b3-bc2f-320740d3ee3a'.
[05/03/2020 12:46:34] Host initialization: ConsecutiveErrors=0, StartupCount=1, OperationId=95bd42f4-1ad7-48b3-bc2f-320740d3ee3a    
[05/03/2020 12:46:34] LoggerFilterOptions
[05/03/2020 12:46:34] {
[05/03/2020 12:46:34]   "MinLevel": "None",
[05/03/2020 12:46:34]   "Rules": [
[05/03/2020 12:46:34]     {
[05/03/2020 12:46:34]       "ProviderName": null,
[05/03/2020 12:46:34]       "CategoryName": null,
[05/03/2020 12:46:34]       "LogLevel": null,
[05/03/2020 12:46:34]       "Filter": "<AddFilter>b__0"
[05/03/2020 12:46:34]     },
[05/03/2020 12:46:34]     {
[05/03/2020 12:46:34]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[05/03/2020 12:46:34]       "CategoryName": null,
[05/03/2020 12:46:34]       "LogLevel": "None",
[05/03/2020 12:46:34]       "Filter": null
[05/03/2020 12:46:34]     },
[05/03/2020 12:46:34]     {
[05/03/2020 12:46:34]       "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
[05/03/2020 12:46:34]       "CategoryName": null,
[05/03/2020 12:46:34]       "LogLevel": null,
[05/03/2020 12:46:34]       "Filter": "<AddFilter>b__0"
[05/03/2020 12:46:34]     }
[05/03/2020 12:46:34]   ]
[05/03/2020 12:46:34] }
[05/03/2020 12:46:34] FunctionResultAggregatorOptions
[05/03/2020 12:46:34] {
[05/03/2020 12:46:34]   "BatchSize": 1000,
[05/03/2020 12:46:34]   "FlushTimeout": "00:00:30",
[05/03/2020 12:46:34]   "IsEnabled": true
[05/03/2020 12:46:34] }
[05/03/2020 12:46:34] SingletonOptions
[05/03/2020 12:46:34] {
[05/03/2020 12:46:34]   "LockPeriod": "00:00:15",
[05/03/2020 12:46:34]   "ListenerLockPeriod": "00:00:15",
[05/03/2020 12:46:34]   "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
[05/03/2020 12:46:34]   "LockAcquisitionPollingInterval": "00:00:05",
[05/03/2020 12:46:34]   "ListenerLockRecoveryPollingInterval": "00:01:00"
[05/03/2020 12:46:34] }
[05/03/2020 12:46:34] HttpOptions
[05/03/2020 12:46:34] {
[05/03/2020 12:46:34]   "DynamicThrottlesEnabled": false,
[05/03/2020 12:46:34]   "MaxConcurrentRequests": -1,
[05/03/2020 12:46:34]   "MaxOutstandingRequests": -1,
[05/03/2020 12:46:34]   "RoutePrefix": "api"
[05/03/2020 12:46:34] }
[05/03/2020 12:46:34] Starting JobHost
[05/03/2020 12:46:34] Starting Host (HostId=cpx99jyb8wg0n5-1469200091, InstanceId=a1f4640b-b2e1-47e3-b876-834653a88555, Version=2.0.13017.0, ProcessId=21700, AppDomainId=1, InDebugMode=False, InDiagnosticMode=False, FunctionsExtensionVersion=(null))
[05/03/2020 12:46:34] Loading functions metadata
[05/03/2020 12:46:34] 1 functions loaded
[05/03/2020 12:46:34] Loading proxies metadata
[05/03/2020 12:46:34] Initializing Azure Function proxies
[05/03/2020 12:46:35] 0 proxies loaded
[05/03/2020 12:46:35] Starting worker process:python  c:\Users\leonidas.nascimento\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd --host 127.0.0.1 --port 9091 --wait "C:\Users\leonidas.nascimento\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.6/WINDOWS/X64/worker.py" --host 127.0.0.1 --port 53324 --workerId 2205d74e-95be-443e-9fae-9280e8f82f93 --requestId bf150909-437c-405a-a9f6-bd00eace0dd5 --grpcMaxMessageLength 134217728
[05/03/2020 12:46:36] python process with Id=11944 started
[05/03/2020 12:46:36] Generating 1 job function(s)
[05/03/2020 12:46:37] Found the following functions:
[05/03/2020 12:46:37] Host.Functions.TimerTrigger
[05/03/2020 12:46:37]
[05/03/2020 12:46:37] Initializing function HTTP routes
[05/03/2020 12:46:37] No HTTP routes mapped
[05/03/2020 12:46:37]
[05/03/2020 12:46:37] Host initialized (2526ms)
[05/03/2020 12:46:39] Executing 'Functions.TimerTrigger' (Reason='Timer fired at 2020-03-05T09:46:39.1799558-03:00', Id=a396db99-58e4-4a4a-95b7-74dee7eb6bb7)
[05/03/2020 12:46:39] Trigger Details: UnscheduledInvocationReason: IsPastDue, OriginalSchedule: 2020-03-05T09:39:00.0000000-03:00
[05/03/2020 12:47:36] Starting worker process failed
[05/03/2020 12:47:36] The operation has timed out.
[05/03/2020 12:47:36] Starting worker process:python  c:\Users\leonidas.nascimento\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd --host 127.0.0.1 --port 9091 --wait "C:\Users\leonidas.nascimento\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.6/WINDOWS/X64/worker.py" --host 127.0.0.1 --port 53324 --workerId ef86ee83-fc02-4dd8-8875-f464a994029d --requestId e557456f-6cb4-4d1e-b87b-a1661f3ea617 --grpcMaxMessageLength 134217728
[05/03/2020 12:47:37] python process with Id=19544 started
[05/03/2020 12:47:42] Starting worker process:python  c:\Users\leonidas.nascimento\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\new_ptvsd\no_wheels\ptvsd --host 127.0.0.1 --port 9091 --wait "C:\Users\leonidas.nascimento\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\python\3.6/WINDOWS/X64/worker.py" --host 127.0.0.1 --port 53324 --workerId e9c8de0b-57bb-4a18-adea-2bc1e6688182 --requestId 1ea5830e-48b3-49e6-8287-38f5fe370209 --grpcMaxMessageLength 134217728
[05/03/2020 12:47:43] python process with Id=1984 started
[05/03/2020 12:47:49] Exceeded language worker restart retry count for runtime:python. Shutting down Functions Host
