### ISSUE TITLE
Dynamic path for inputBlob

### ISSUE THREAD

**Issue by iMicknl** [Azure/azure-functions-python-worker#701]
###### Please provide the following:

- Core Tools version: 3.0.2596

###### Provide the steps required to reproduce the problem:

1. Create a Durable Function Activty in Python
1. Add an input binding for blob
1. Set "path": "{path}"

###### Provide a description of the expected behavior.
It would resolve the blob.

###### Provide a description of the actual behavior observed.

The validation failed, even though the path + file exists. When I add the same path hardcoded in the function.json definition, the input binding works.

```
[06/24/2020 11:01:29] Executed 'Functions.PreprocessForm' (Failed, Id=db060c7b-c945-4150-a3c2-d04715baac23)
[06/24/2020 11:01:29] System.Private.CoreLib: Exception while executing function: Functions.PreprocessForm. Microsoft.Azure.WebJobs.Host: Validation failed for property 'BlobPath', value '"forms/test6.pdf"'. The field BlobPath is invalid.
```

<details>
```
[06/24/2020 11:01:29] 7c2c9389a97f482abf08ec11377b2047: Function 'PreprocessForm (Activity)' failed with an error. Reason: System.InvalidOperationException: Validation failed for property 'BlobPath', value '"forms/test6.pdf"'. The field BlobPath is invalid.
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.<>c__DisplayClass11_0.<GetValidatorFunc>b__0(Object value) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\AttributeCloner.cs:line 217
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.TemplateBind(IResolutionPolicy policy, PropertyInfo prop, Attribute attr, BindingTemplate template, IReadOnlyDictionary`2 bindingData, Action`1 validator) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\AttributeCloner.cs:line 378
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.<>c__DisplayClass13_0.<GetTemplateResolver>b__0(Attribute newAttr, IReadOnlyDictionary`2 bindingData) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\AttributeCloner.cs:line 262
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.<>c__DisplayClass20_0.<ResolveFromBindings>b__0(Func`3 func) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\AttributeCloner.cs:line 357
[06/24/2020 11:01:29]    at System.Array.ConvertAll[TInput,TOutput](TInput[] array, Converter`2 converter)
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.ResolveFromBindings(IReadOnlyDictionary`2 bindingData) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\AttributeCloner.cs:line 357
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.ResolveFromBindingData(BindingContext ctx) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\AttributeCloner.cs:line 306
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Host.Bindings.BindingBase`1.BindAsync(BindingContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\BindingBase.cs:line 49
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Binder.BindAsync[TValue](Attribute[] attributes, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\Runtime\Binder.cs:line 108
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Script.Binding.FunctionBinding.BindStreamAsync(BindingContext context, FileAccess access) in D:\a\1\s\src\WebJobs.Script\Binding\FunctionBinding.cs:line 226
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Script.Binding.ExtensionBinding.BindAsync(BindingContext context) in D:\a\1\s\src\WebJobs.Script\Binding\ExtensionBinding.cs:line 63
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.<>c__DisplayClass10_0.<<BindInputsAsync>b__1>d.MoveNext() in D:\a\1\s\src\WebJobs.Script\Description\Workers\WorkerFunctionInvoker.cs:line 128
[06/24/2020 11:01:29] --- End of stack trace from previous location where exception was thrown ---
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.BindInputsAsync(Binder binder) in D:\a\1\s\src\WebJobs.Script\Description\Workers\WorkerFunctionInvoker.cs:line 131
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in D:\a\1\s\src\WebJobs.Script\Description\Workers\WorkerFunctionInvoker.cs:line 64
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in D:\a\1\s\src\WebJobs.Script\Description\FunctionInvokerBase.cs:line 85
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) in D:\a\1\s\src\WebJobs.Script\Description\FunctionGenerator.cs:line 225
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 585
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 532
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 470
[06/24/2020 11:01:29]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 278. IsReplay: False. State: Failed. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.8.5. SequenceNumber: 7.
```
</details>

###### Provide any related information

* Links to source
* Bindings used

<details>
<summary>Source</summary>

```python
# __init__.py

# This function is not intended to be invoked directly. Instead it will be
# triggered by an orchestrator function.

import logging

import os
import io

import azure.functions as func

import filetype
import numpy as np
import cv2

# pylint: disable=unsubscriptable-object
def main(path: str, inputBlob: func.InputStream, outputBlob: func.Out[func.InputStream]) -> str:

    logging.warning(
        f"Orchestrator handled \n"
        f"Name: {inputBlob.name}\n"
        f"Blob Size: {inputBlob.length} bytes"
    )

    outputBlob.set(inputBlob)
    
    return f"Specified path is {path}!"
```

```json
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "path",
      "type": "activityTrigger",
      "direction": "in"
    },
    {
      "name": "inputBlob",
      "type": "blob",
      "dataType": "binary",
      "path": "{path}",
      "connection": "pythonfrpipeline_STORAGE",
      "direction": "in"
    },
    {
      "name": "outputBlob",
      "type": "blob",
      "path": "{path}-PROCESSED",
      "connection": "pythonfrpipeline_STORAGE",
      "direction": "out"
    }
  ]
}
```
</details>

**Comment by Statowfiq** [comment]
I do have the same issue.

**Comment by Statowfiq** [comment]
@iMicknl  Did you manage to resolve this issue?

**Comment by iMicknl** [comment]
@Statowfiq no, I did use the Azure Storage Python SDK (which is excellent!) as a workaround.

**Comment by Statowfiq** [comment]
I managed to resolve it. 
Here is how i resolved it.

Create a environment variable in your `local.settings.json`

`"BLOBNAME":"YOUR_BLOB_CONTAINER_NAME"`

Refer your env variable in your function.json using % sign
`{
  "entryPoint": "blobTrigger",
  "bindings": [
    {
      "name": "myBlob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "%BLOBNAME%/{name}.csv",
      "connection": "AzureWebJobsStorage"
    }
  ],
  "scriptFile": "../dist/functionName/index.js"
}
`

**Comment by stefanushinardi** [comment]
Late reply, but I think the original ask of this thread might be solved better by using Azure SDK

**Comment by waltherg** [comment]
> Late reply, but I think the original ask of this thread might be solved better by using Azure SDK

@stefanushinardi the original ask seems pretty basic in how it tries to use Azure Functions bindings. Does your response mean we're not supposed to use bindings in combination with blob storage in general?

**Comment by stefanushinardi** [comment]
Hello @waltherg, totally agree with you that the use case is very common. Unfortunately, due to the host and python worker architecture, the change that is required is not trivial (at python worker level, we do not have access to the rich object that makes the call to services). There is a plan on the roadmap to have this functionality, but there is no ETA that we can communicate yet. 

I would like to clarify regarding the guidance of using bindings with blob storage (or in fact all services). Users should use bindings whenever they increase developers productivity (e.g. writing less boilerplate code and managing connections). There are limitations for out-of-proc workers(e.g. python, node) currently, and we plan to close the gap in the future. But at the end of the day, bindings are an abstraction. Potentially, the abstraction does not fit with every single use cases. This is where the use of SDK might make more sense.

I hope what I wrote clarify certain things I'd be happy to chat if there are more questions regarding this. Thanks!

**Comment by waltherg** [comment]
@stefanushinardi thanks for your thorough and clarifying comment.

This may then just be an issue of documentation? To my mind it's totally understandable these technical limitations exist for e.g. Python, however they don't appear to be documented.

Take this page for instance:

https://docs.microsoft.com/en-us/azure/azure-functions/functions-triggers-bindings?tabs=python

I may have missed it but didn't notice any mention of these limitations there.
