### ISSUE TITLE
Error during local build: Failing to install dask (crashing during pyyaml build)

### ISSUE THREAD

**Issue by Servot** [Azure/azure-functions-python-worker#776]
I am building an Azure Function using the VSCode extension.
My requirements.txt file contains, among other `dask`.

When trying to run the function locally (i.e. pressing `F5` in VSCode), the app crashes when running `pip install -r requirements.txt`:

```
Executing task: .venv/bin/python -m pip install -r requirements.txt <

Requirement already satisfied: azure-functions in ./.venv/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: azure-storage-blob==2.1 in ./.venv/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (2.1.0)
Requirement already satisfied: wheel in ./.venv/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (0.35.1)
Collecting dask
  Using cached dask-2.30.0-py3-none-any.whl (848 kB)
Requirement already satisfied: matplotlib in ./.venv/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (3.3.2)
Requirement already satisfied: numpy in ./.venv/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (1.19.4)
Requirement already satisfied: pandas in ./.venv/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (1.1.4)
Requirement already satisfied: scikit-learn in ./.venv/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (0.23.2)
Collecting termcolor
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
source /opt/anaconda3/bin/activate
conda activate base
Collecting tqdm
  Using cached tqdm-4.51.0-py2.py3-none-any.whl (70 kB)
Collecting xlrd
  Using cached xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
Requirement already satisfied: azure-storage-common~=2.1 in ./.venv/lib/python3.7/site-packages (from azure-storage-blob==2.1->-r requirements.txt (line 6)) (2.1.0)
Requirement already satisfied: azure-common>=1.1.5 in ./.venv/lib/python3.7/site-packages (from azure-storage-blob==2.1->-r requirements.txt (line 6)) (1.1.25)
Collecting pyyaml
  Using cached PyYAML-5.3.1.tar.gz (269 kB)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.venv/lib/python3.7/site-packages (from matplotlib->-r requirements.txt (line 9)) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in ./.venv/lib/python3.7/site-packages (from matplotlib->-r requirements.txt (line 9)) (8.0.1)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.7/site-packages (from matplotlib->-r requirements.txt (line 9)) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in ./.venv/lib/python3.7/site-packages (from matplotlib->-r requirements.txt (line 9)) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in ./.venv/lib/python3.7/site-packages (from matplotlib->-r requirements.txt (line 9)) (2.4.7)
Requirement already satisfied: certifi>=2020.06.20 in ./.venv/lib/python3.7/site-packages (from matplotlib->-r requirements.txt (line 9)) (2020.6.20)
Requirement already satisfied: pytz>=2017.2 in ./.venv/lib/python3.7/site-packages (from pandas->-r requirements.txt (line 11)) (2020.4)
Requirement already satisfied: scipy>=0.19.1 in ./.venv/lib/python3.7/site-packages (from scikit-learn->-r requirements.txt (line 13)) (1.5.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.venv/lib/python3.7/site-packages (from scikit-learn->-r requirements.txt (line 13)) (2.1.0)
Requirement already satisfied: joblib>=0.11 in ./.venv/lib/python3.7/site-packages (from scikit-learn->-r requirements.txt (line 13)) (0.17.0)
Requirement already satisfied: cryptography in ./.venv/lib/python3.7/site-packages (from azure-storage-common~=2.1->azure-storage-blob==2.1->-r requirements.txt (line 6)) (3.2.1)
Requirement already satisfied: requests in ./.venv/lib/python3.7/site-packages (from azure-storage-common~=2.1->azure-storage-blob==2.1->-r requirements.txt (line 6)) (2.24.0)
Requirement already satisfied: six in ./.venv/lib/python3.7/site-packages (from cycler>=0.10->matplotlib->-r requirements.txt (line 9)) (1.15.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in ./.venv/lib/python3.7/site-packages (from cryptography->azure-storage-common~=2.1->azure-storage-blob==2.1->-r requirements.txt (line 6)) (1.14.3)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./.venv/lib/python3.7/site-packages (from requests->azure-storage-common~=2.1->azure-storage-blob==2.1->-r requirements.txt (line 6)) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in ./.venv/lib/python3.7/site-packages (from requests->azure-storage-common~=2.1->azure-storage-blob==2.1->-r requirements.txt (line 6)) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in ./.venv/lib/python3.7/site-packages (from requests->azure-storage-common~=2.1->azure-storage-blob==2.1->-r requirements.txt (line 6)) (3.0.4)
Requirement already satisfied: pycparser in ./.venv/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography->azure-storage-common~=2.1->azure-storage-blob==2.1->-r requirements.txt (line 6)) (2.20)
Building wheels for collected packages: termcolor, pyyaml
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4830 sha256=44b0496d2d5e8bd7116721f427c0b4bb593459f76c9eaac8e0ec44166b2cc990
  Stored in directory: /Users/<user>/Library/Caches/pip/wheels/3f/e3/ec/8a8336ff196023622fbcb36de0c5a5c218cbb24111d1d4c7f2
  Building wheel for pyyaml (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/<user>/<project>/azurefunction/.venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-install-857ug4su/pyyaml/setup.py'"'"'; __file__='"'"'/private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-install-857ug4su/pyyaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-wheel-rp1fq77p
       cwd: /private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-install-857ug4su/pyyaml/
  Complete output (63 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.15-x86_64-3.7
  creating build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/scanner.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/error.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/constructor.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/composer.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/events.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/representer.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/tokens.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/dumper.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/cyaml.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/parser.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/reader.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/loader.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/resolver.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/serializer.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/nodes.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  copying lib3/yaml/emitter.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-install-857ug4su/pyyaml/setup.py", line 314, in <module>
      python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*',
    File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/<user>/<project>/azurefunction/.venv/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-install-857ug4su/pyyaml/setup.py", line 185, in run
      _build_ext.run(self)
    File "/Users/<user>/<project>/azurefunction/.venv/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 310, in run
      customize_compiler(self.compiler)
    File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/sysconfig.py", line 188, in customize_compiler
      _osx_support.customize_compiler(_config_vars)
    File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_osx_support.py", line 429, in customize_compiler
      _find_appropriate_compiler(_config_vars)
    File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_osx_support.py", line 167, in _find_appropriate_compiler
      if not _find_executable(cc):
    File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_osx_support.py", line 36, in _find_executable
      path = os.environ['PATH']
    File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 681, in __getitem__
      raise KeyError(key) from None
  KeyError: 'PATH'
  ----------------------------------------
  ERROR: Failed building wheel for pyyaml
  Running setup.py clean for pyyaml
Successfully built termcolor
Failed to build pyyaml
Installing collected packages: pyyaml, dask, termcolor, tqdm, xlrd
    Running setup.py install for pyyaml ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/<user>/<project>/azurefunction/.venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-install-857ug4su/pyyaml/setup.py'"'"'; __file__='"'"'/private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-install-857ug4su/pyyaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-record-uc88s6oe/install-record.txt --single-version-externally-managed --compile --install-headers /Users/<user>/<project>/azurefunction/.venv/include/site/python3.7/pyyaml
         cwd: /private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-install-857ug4su/pyyaml/
    Complete output (65 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.15-x86_64-3.7
    creating build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/scanner.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/error.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/constructor.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/composer.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/events.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/representer.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/tokens.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/dumper.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/cyaml.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/parser.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/reader.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/loader.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/resolver.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/serializer.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/nodes.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    copying lib3/yaml/emitter.py -> build/lib.macosx-10.15-x86_64-3.7/yaml
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-install-857ug4su/pyyaml/setup.py", line 314, in <module>
        python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*',
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/<user>/<project>/azurefunction/.venv/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-install-857ug4su/pyyaml/setup.py", line 185, in run
        _build_ext.run(self)
      File "/Users/<user>/<project>/azurefunction/.venv/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 310, in run
        customize_compiler(self.compiler)
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/sysconfig.py", line 188, in customize_compiler
        _osx_support.customize_compiler(_config_vars)
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_osx_support.py", line 429, in customize_compiler
        _find_appropriate_compiler(_config_vars)
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_osx_support.py", line 167, in _find_appropriate_compiler
        if not _find_executable(cc):
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_osx_support.py", line 36, in _find_executable
        path = os.environ['PATH']
      File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 681, in __getitem__
        raise KeyError(key) from None
    KeyError: 'PATH'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/<user>/<project>/azurefunction/.venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-install-857ug4su/pyyaml/setup.py'"'"'; __file__='"'"'/private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-install-857ug4su/pyyaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/3b/pcxn97rs1f96rb15k8dv33nr0000gq/T/pip-record-uc88s6oe/install-record.txt --single-version-externally-managed --compile --install-headers /Users/<user>/<project>/azurefunction/.venv/include/site/python3.7/pyyaml Check the logs for full command output.
```

I am using a macOS v10.15.3, python version is 3.7.8.
When trying to pip install `dask` in the terminal (outside of VSCode), it works just fine.

A get a similar error when trying to install e.g. `scikit-garden`.

**Comment by Hazhzeng** [comment]
Hi @Servot,

Thanks for reporting this issue.

This seems like an issue when building pyyaml macOS wheel, could be related to the VSCode Python Extension, I would suggest upgrade your Python VSCode Extension and checkout https://github.com/microsoft/vscode-python/issues/436#issuecomment-361801116

Let me know if you have any questions.
