### ISSUE TITLE
Exception while executing function: ... Did not find any initialized language workers

### ISSUE THREAD

**Issue by geg00** [Azure/azure-functions-python-worker#853]
#### Check for a solution in the Azure portal
For issues in production, please check for a solution to common issues in the Azure portal before opening a bug. In the Azure portal, navigate to your function app, select `Diagnose and solve problems` from the left, and view relevant dashboards before opening your issue.

I'm getting 404 Not Found nginx when execu
ting function 
But on the Live Metrics I'm getting
Time	9:55:52 PM

```
Exception type	Microsoft.Azure.WebJobs.Host.FunctionInvocationException
Exception message	Exception while executing function: Functions.HttpTrigger1 <--- Did not find any initialized language workers
ProcessId	59
prop__TriggerReason	This function was programmatically called via the host APIs.
prop__Succeeded	False
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.HttpTrigger1
 ---> System.InvalidOperationException: Did not find any initialized language workers
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcherLoadBalancer.GetLanguageWorkerChannel(IEnumerable`1 rpcWorkerChannels, Int32 maxProcessCount) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcherLoadBalancer.cs:line 27
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcFunctionInvocationDispatcher.InvokeAsync(ScriptInvocationContext invocationContext) in /src/azure-functions-host/src/WebJobs.Script/Workers/Rpc/FunctionRegistration/RpcFunctionInvocationDispatcher.cs:line 283
   at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /src/azure-functions-host/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 93
   at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82
   at Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionGenerator.cs:line 225
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 555
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 501
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 279
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 326
```

#### Investigative information

Please provide the following:

- Timestamp:  All the time
- Function App version:   
- Function App name: HttpTrigger1
- Function name(s) (as appropriate):
- Invocation ID: 
- Region: US Central

#### Repro steps

Provide the steps required to reproduce the problem:

#### Expected behavior

Provide a description of the expected behavior.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used   python 
* Links to source
* Bindings used

**Comment by v-anvari** [comment]
Tagging @Hazhzeng for any inputs

**Comment by Hazhzeng** [comment]
Hi @geg00 could you share me with your application name?

**Comment by geg00** [comment]
https://kd1234.azurewebsites.net/api/HttpTrigger1
https://kd1234.azurewebsites.net/api/HttpTrigger2

**Comment by Hazhzeng** [comment]
Hi @kd1234, thanks for reporting this issue. From our backend, we saw `Microsoft.Azure.WebJobs.Script.Workers.WorkerProcessExitException : python exited with code 137` errors from our backend. This usually means the package size is too large for a Linux Consumption function app since it has a [service limitation of 1.5GB memory](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits). Reduce the memory footprint or using a better SKU (e.g. App Service Plan) may resolve this issue.
