### ISSUE TITLE
[BUG] Exception error when using return for out binding to EventHub 

### ISSUE THREAD

**Issue by MMollyy** [Azure/azure-functions-python-worker#861]
###### Please provide the following:
the function app name name i will not disclose as it contain functional naming to our environment.

- Timestamp: Many. I've been getting the error for over 24hours now.
- Function App name: functionapp1
- Function name(s) (as appropriate): EventHubTrigger
- Core Tools version: 3.0.3442

###### Provide the steps required to reproduce the problem:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-output?tabs=python

I basically followed the example from the docs. I'm trying to create my own message on an eventhub.

###### Provide a description of the expected behavior.

I would expect a message to be created on the eventhub when using the output binding, however it seems to error on some kind of datum type that is being expected. Yet the docs don't mention such a thing and I have not found any other examples where such a variable would be used.

###### Provide a description of the actual behavior observed.
Function runs until the point where the return value is given, and then gives the following error:
```
Exception while executing function: Functions.EventHubTrigger <--- Result: Failure Exception: NotImplementedError: unexpected Datum type: None Stack: File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 425, in _handle__invocation_request pytype=fi.return_type.pytype) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/bindings/meta.py", line 117, in to_outgoing_proto return datumdef.datum_as_proto(datum) File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/bindings/datumdef.py", line 191, in datum_as_proto 'unexpected Datum type: {!r}'.format(datum.type)
```

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.EventHubTrigger
 ---> Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Failure
Exception: NotImplementedError: unexpected Datum type: None
Stack:   File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 425, in _handle__invocation_request
    pytype=fi.return_type.pytype)
  File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/bindings/meta.py", line 117, in to_outgoing_proto
    return datumdef.datum_as_proto(datum)
  File "/azure-functions-host/workers/python/3.7/LINUX/X64/azure_functions_worker/bindings/datumdef.py", line 191, in datum_as_proto
    'unexpected Datum type: {!r}'.format(datum.type)

   at Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters, FunctionInvocationContext context) in /src/azure-functions-host/src/WebJobs.Script/Description/Workers/WorkerFunctionInvoker.cs:line 93
   at Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) in /src/azure-functions-host/src/WebJobs.Script/Description/FunctionInvokerBase.cs:line 82
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 555
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 501
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 279
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 326
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 94
```

###### Provide a description of any known workarounds.

I can put the `return` into a comment and the error will disappear.

###### Provide the requirements.txt file to help us find out module related issues.

```
# Do not include azure-functions-worker as it may conflict with the Azure Functions platform

azure-functions==1.7.0
azure-cosmosdb-table==1.0.6
azure-eventhub==5.5.0
azure-keyvault-secrets==4.2.0
azure-identity==1.6.0
requests==2.25.1
```
-->

###### Provide any related information

<details>
<summary>Source</summary>

```python
# __init__.py
from typing import List

import logging
import json
import requests
import datetime

import azure.functions as func

from azure.cosmosdb.table.tableservice import TableService
from azure.common import AzureMissingResourceHttpError
from azure.core.exceptions import ResourceNotFoundError

from .keyvault import get_keyvault_secret

from .configuration import (
    ALLOWED_ACTIONS,
    ENVIRONMENT,
    TABLE_NAME
)

cdb_connection_string = get_keyvault_secret(secret_item_name='cosmosdb-connection-string')
azure_table_service = TableService(connection_string=cdb_connection_string)


def get_azure_table_row(nsg_name, number):
    try:
        entity_lookup = azure_table_service.get_entity(TABLE_NAME, nsg_name, number)
    except AzureMissingResourceHttpError as e:
        if e.status_code == 200:
            entity_lookup = azure_table_service.get_entity(TABLE_NAME, nsg_name, number)
            return entity_lookup
        else:
            logging.error(f'#### Status Code: {e.status_code} ####')
            return []
    else:
        return entity_lookup


def create_azure_table_entity(nsg_name, number):
    payload = {
        'PartitionKey': nsg_name,
        'RowKey': number,
        'environment': ENVIRONMENT,
        'skip': 'false'
    }
    create_entity = azure_table_service.insert_entity(TABLE_NAME, payload)
    return create_entity

def main(events: List[func.EventHubEvent]) -> str:
    logging.info('function started ...')
    for event in events:
        json_string = event.get_body().decode('utf-8')
        json_object = json.loads(json_string)
        logging.info(f'------------------------------------------------------------------------------ {len(json_object["records"])} ------------------------------------------------------------------------------')
        logging.info(f'json object created, starting validation..')
        for item in json_object["records"]:
            if "properties" not in item.keys() or item["properties"]["message"] not in ALLOWED_ACTIONS:
                logging.info(f'{item["properties"]["message"]} for resource: {item["resourceId"].lower().split("/")[-1]} with ResultType: {item["resultType"]}')
                logging.info(f'No action was taken. The parsed activity log did not relate to an action for a NSG on the Microsoft.Network resource provider.')
            else:
                logging.info('Found administrative log to parse, parsing now ..')
                if "properties" in item.keys() and item["properties"]["message"] in ALLOWED_ACTIONS and item["resultType"] == "Success":
                    logging.info('Administrative log with successful action found, checking if write or delete action to Cosmos DB is required ..')
                    resourceid = item["resourceId"].lower().split('/')
                    number = resourceid[4][-3:]
                    nsg_name = resourceid[-1]
                    if "write" in item["properties"]["message"].lower():
                        logging.info('(new) NSG update found in log ..')
                        validation = get_azure_table_row(nsg_name, number)
                        if validation:
                            logging.info(f'No action was taken. {nsg_name} already exists.')
                        elif not validation:
                            logging.info(f'Adding entry in CosmosDB {TABLE_NAME} for {nsg_name}')
                            creation = create_azure_table_entity(nsg_name, number)
                            logging.info(f"Finished creating item in CosmosDB ..")
                            payload = {"nsg-name": nsg_name, "number": number, "log_type": "create"}
                            timestamp = datetime.datetime.utcnow()
                            logging.info('Message created at: %s', timestamp)
                            #return 'Message created at: {}'.format(timestamp)
                    elif "delete" in item["properties"]["message"].lower():
                        logging.info(f'Deleting entry in CosmosDB {TABLE_NAME} for {nsg_name}')
                        try:
                            azure_table_service.delete_entity(TABLE_NAME, nsg_name, number)
                            payload = {"nsg-name": nsg_name, "number": number, "log_type": "delete"}
                            #return json.dumps(payload)
                        except ResourceNotFoundError:
                            logging.info('Entry did not exist in CosmosDB ..')
                else:
                    logging.info(f'No action was taken. The activity log did not contain a successful write or delete action for a NSG on the Microsoft.Network resource provider.')

```

```
#function.json
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "type": "eventHubTrigger",
      "name": "events",
      "direction": "in",
      "eventHubName": "in-eventhub",
      "connection": "eventhub_connection",
      "cardinality": "many",
      "consumerGroup": "$Default",
      "dataType": "string"
    },
    {
      "type": "eventHub",
      "name": "$return",
      "eventHubName": "out-eventhub",
      "connection": "MyEventHubSendAppSetting",
      "direction": "out"
    }
  ]
}
```

</details>
-->

additional:
- both connection settings in the function.json are in the app settings of the functionapp. 
- The inbound binding works like a charm
- All the keyvault secret lookups work as well
- I am a beginner with azure functions
- requests library is in my requirements file because I am trying to trigger a HTTP azure function, but that's also not working for some reason. That's a whole different story..

**Comment by NoelGK** [comment]
I have the same problem, even if I do not provide any "return" statement. The template code provided in [the azure documentation](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=in-process%2Cfunctionsv2%2Cextensionv5&pivots=programming-language-python#example) works fine until the logging.info() statements finish. Then, it throws the error 

> NotImplementedError: unexpected Datum type: None

and bla bla bla.

**Comment by JordiNeil** [comment]
Same issue here

**Comment by alf5koe** [comment]
Same here. How can you send a message to an EventHub using python?

**Comment by hallvictoria** [comment]
Hi, is this issue still occurring? I created an [EventHub trigger function](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=python-v2%2Cin-process%2Cnodejs-v4%2Cfunctionsv2%2Cextensionv5&pivots=programming-language-python#example) and [EventHub output function](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-output?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cfunctionsv2%2Cextensionv5&pivots=programming-language-python#example) using the documentation mentioned earlier, and the functions executed as expected. I tried both V1 and V2 programming models with core tools version 4.0.5907, and all functions executed successfully.

<details>
<summary>Code:</summary>

```
import azure.functions as func
import logging

app = func.FunctionApp()

@app.event_hub_message_trigger(arg_name="azeventhub",
                               event_hub_name="<eventhub_name>",
                               connection="<eventhub_connection>") 
def eventhub_trigger(azeventhub: func.EventHubEvent):
    logging.info('Python EventHub trigger processed an event: %s',
                azeventhub.get_body().decode('utf-8'))


@app.function_name(name="eventhub_output")
@app.route(route="eventhub_output")
@app.event_hub_output(arg_name="event",
                      event_hub_name="<eventhub_name>",
                      connection="<eventhub_connection>")
def eventhub_output(req: func.HttpRequest, event: func.Out[str]):
    body = req.get_body()
    if body is not None:
        event.set(body.decode('utf-8'))
    else:    
        logging.info('req body is none')
    return 'ok'
```
</details>

<details>
<summary>Output:</summary>

```
[2024-08-09T17:34:50.628Z] Executing 'Functions.eventhub_output' (Reason='This function was programmatically called via the host APIs.', Id=718611d9-a932-42e2-af90-a9af8a0f2142)
[2024-08-09T17:34:50.699Z] Received FunctionInvocationRequest, request ID: f75028d5-a0a3-45d8-89ab-ce6d1c9d6d27, function ID: fddb0166-16cc-533e-b35c-0e3d596bdc8f, function name: eventhub_output, invocation ID: 718611d9-a932-42e2-af90-a9af8a0f2142, function type: sync, timestamp (UTC): 2024-08-09 17:34:50.693079, sync threadpool max workers: 1000
[2024-08-09T17:34:52.284Z] Executed 'Functions.eventhub_output' (Succeeded, Id=718611d9-a932-42e2-af90-a9af8a0f2142, Duration=1677ms)
[2024-08-09T17:34:52.318Z] Executed HTTP request: {
[2024-08-09T17:34:52.320Z]   "requestId": "fe3aef35-381a-42e6-bd0d-aa748b663c7b",
[2024-08-09T17:34:52.324Z]   "identities": "(WebJobsAuthLevel:Admin)",
[2024-08-09T17:34:52.327Z]   "status": "200",
[2024-08-09T17:34:52.329Z]   "duration": "1884"
[2024-08-09T17:34:52.330Z] }
[2024-08-09T17:34:52.421Z] Executing 'Functions.eventhub_trigger' (Reason='(null)', Id=e1b4d2b3-84f1-4ecf-a2a5-6042f65800a7)
[2024-08-09T17:34:52.427Z] Trigger Details: PartionId: 1, Offset: 4294968000, EnqueueTimeUtc: 2024-08-09T17:34:51.0980000Z, SequenceNumber: 7, Count: 1
[2024-08-09T17:34:52.450Z] Received FunctionInvocationRequest, request ID: f75028d5-a0a3-45d8-89ab-ce6d1c9d6d27, function ID: 1b91b932-ee24-5349-bdef-4ec3b60cf9ec, function name: eventhub_trigger, invocation ID: e1b4d2b3-84f1-4ecf-a2a5-6042f65800a7, function type: sync, timestamp (UTC): 2024-08-09 17:34:52.440762, sync threadpool max workers: 1000
[2024-08-09T17:34:52.462Z] Executed 'Functions.eventhub_trigger' (Succeeded, Id=e1b4d2b3-84f1-4ecf-a2a5-6042f65800a7, Duration=49ms)
```
</details>
