### ISSUE TITLE
Help Debugging "azure.identity._exceptions.CredentialUnavailableError: Azure CLI not found on path"

### ISSUE THREAD

**Issue by fergalm** [Azure/azure-functions-python-worker#934]
#### Is your question related to a specific version? If so, please specify:
No

#### What binding does your question apply to, if any? (e.g. Blob Trigger, Event Hub Binding, etc) 
HttpTrigger

#### Question
I have a HttpTrigger that runs final locally using Visual Studio Code's debugging facility, but fails when I deploy to the cloud. The httptrigger code is

```
    try:
        prod.predict_peak.main(datestr, cfgfile)  #My actual code
    except Exception as e:
        tb = traceback.format_exc()
        msg = f"<P>Code failed with this error: {e}. Traceback is </P><PRE>{tb}</PRE>"
        return func.HttpResponse(msg, mimetype="text/html", status_code=500)
    return func.HttpResponse(f"Code ran to completion for {region} on {datestr}")
```

and the response is
```
Code failed with this error: Azure CLI not found on path. Traceback is

Traceback (most recent call last):
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_credentials/azure_cli.py", line 141, in _run_command
    return subprocess.check_output(args, **kwargs)
  File "/usr/local/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'az account get-access-token --output json --resource https://vault.azure.net']' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/site/wwwroot/HttpTrigger1/__init__.py", line 35, in main
    prod.predict_peak.main(datestr, cfgfile)
  File "/home/site/wwwroot/prod/predict_peak.py", line 61, in main
    secrets = get_secrets(
  File "/home/site/wwwroot/prod/getsecret.py", line 38, in get_secrets
    out[name] = client.get_secret(name)._value
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/keyvault/secrets/_client.py", line 67, in get_secret
    bundle = self._client.get_secret(
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/keyvault/secrets/_generated/_operations_mixin.py", line 1515, in get_secret
    return mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/keyvault/secrets/_generated/v7_2/operations/_key_vault_client_operations.py", line 286, in get_secret
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/core/pipeline/policies/_retry.py", line 445, in send
    response = self.next.send(request)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 111, in send
    self._handle_challenge(request, challenge)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 137, in _handle_challenge
    self._token = self._credential.get_token(scope)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_internal/decorators.py", line 30, in wrapper
    token = fn(*args, **kwargs)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_credentials/azure_cli.py", line 73, in get_token
    output = _run_command(command)
  File "/home/site/wwwroot/.python_packages/lib/site-packages/azure/identity/_credentials/azure_cli.py", line 145, in _run_command
    raise CredentialUnavailableError(message=CLI_NOT_FOUND)
azure.identity._exceptions.CredentialUnavailableError: Azure CLI not found on path
```

Digging into the stack trace, the problem arises in this function of mine:
```
import azure.keyvault.secrets
import azure.identity

def get_secrets(vault, *secretNames):
    KvUri = f"https://{vault}.vault.azure.net"

    credential = azure.identity.AzureCliCredential()
    client = azure.keyvault.secrets.SecretClient(vault_url=KvUri, credential=credential)

    out = dict()
    for name in secretNames:
        out[name] = client.get_secret(name)._value  #This line raises the exception
    return out
```

Somewhere in this code, there is a system call to `az account get-access-token `, which fails because az can't be found on the path. I'm stumped by this problem because (a) it works locally, and (b), azure-cli is included in my requirements.txt

```
#requirements.txt

# DO NOT include azure-functions-worker in this file
# The Python Worker is managed by Azure Functions platform
# Manually managing azure-functions-worker may cause unexpected issues

adlfs
azure-cli==2.30.0
azure-functions
azure-identity
azure-keyvault-secrets
colorama
fsspec
ipdb
gitpython
matplotlib
numpy
pandas
scipy
shooju
toml
tqdm
```

I've really no idea how to debug this problem. Am I just missing a line in my requirements file? Do I need to add something to my PATH variable? What steps should I take next?

**Comment by fergalm** [comment]
Update: I worked around the problem by changing the line
`credential = azure.identity.AzureCliCredential()`
to
`credential = azure.identity.DefaultAzureCredential()`

I'm guessing (I'm new at this), that I should have been using the default credential class from the the start. I'm closing this as probably not worth anyone's time to investigate.
